# notes: 
# To implement updates, call;
#  blogdown::serve_site()

# resources at: 
# https://gohugo.io/templates

# URL to find page in browser, other files at 
# baseURL / ...
baseURL = "https://macstrelioff.github.io"

title = "Mac Strelioff"
theme = "hugo-theme-techdoc"
languageCode = "en-us"
DefaultContentLanguage = "en"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

publishDir = "./"

[Params]
    # Souce Code repository section
    # description = "" # like a subtitle
    #github_repository = "https://github.com/thingsym/hugo-theme-techdoc"
    github_repository = "https://github.com/macstrelioff" # link for github theme
    # version = "0.2.2" # small text left of title prepended by 'version'

    # Documentation repository section 
    # documentation repository (set edit link to documentation repository)
    # github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"

    # Analytic section
    google_analytics_id      = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name folders excluded from side menu
    menu_exclusion = ["archives", "entry", "post", "posts","themes","blog","getting-started","hugo-theme-techdoc",""]


# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"  # directs to a folder in .
    weight = 1
    
[[menu.main]]
    name = "About"
    url = "/about"  # directs to a folder in ??
    weight = 2

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/thingsym"
    weight = 3
    
[[menu.main]]
    name = "Blog"
    url = "/blog" 
    weight = 4
