---
title: "Growing Smarter: Understanding User Acquisition"
author: "Mac Strelioff"
date: 
math: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Insight

Insight is a data science fellowship where Fellows work on a 2 week project. For my project, I consulted with Elastic Projects to understand user conversion on their product, [Abstract](https://www.abstract.com/). Abstract is a file sharing and versioning application, much like GitHub, with an emphasis on digital artwork.

Explain notion of user/org, contributor, viewer, and guest -- this comes up later when justifying the per contributor features.

<!--- borrow information from Abstract's website --->

# Business Value and Project Goals

The survival of any company hinges on it's ability to acquire new users. One way that Elastic Projects acquires users is through a 30-day free trial of their product, [Abstract](https://www.abstract.com/). However, around 80\% of free-trial users fail to convert to paying customers. This leaves much opportunity to increase their userbase.

## Project Goals

As a consultant for Elastic Projects, I helped with two major goals focused on issuing nudges to users in order to increase the probability of conversion to a paid customer;

1. As early as possible, identify which users to nudge
2. Determine how to nude them.

## Original Beliefs

complex features were the source of Abstract's value to users, and hence were the features driving user conversion. 

<!--- 
My work presented here helped Elastic Projects to identify ways to increase the proportion of users that subscribe for paid service by uncovering usage behavior most indicative of a propensity to convert. 
--->

Question: Do product issues stop users from engaging with the app?

# Thinking

Payers and non-payers might differ in distributions of activity

Those who end up paying might differ in the distribution of these engagement metrics.

This lead to exploration that focused on these distributions

This lead to LDA and QDA as the first algorithms that I considered.


# Data sources and processing
<!---(exclude clearbit)--->

The original dataset consisted of user activity and product performance data for all users over a one year period. There were a large number of users included in the dataset. The dataset also included users that were not germain to the central problem of identifying which free-trial users to nudge. Since the primary goal was to identify free-trial users to nudge, I excluded any users who were never on a free trial during the data collection period. In exploratory analysis, I found a large number of users who never showed any activity. This prompted me to believe there are two types of trial users that do not convert -- 1) those who make an account then never engage with the product, and 2) those who engage with the product, then decide to stop engagement. In conversation with Elastic Projects, it seemed that making a commit was a baseline for minimal engagement with the project, so, to focus the analysis on users who at least minimally engaged with the product, I also excluded users who never made a commit. Finally, some product features were not avilable during the full duration of data collection. Since there was a large sample size, the easiest way to make the analyses pertenant for all features was to exclude data collected before all product features were available. 

## Feature Engineering

The original user activity data was in terms of counts of an action (e.g. file edit) on each date. To make the users comparible to each other, I created a new variable for account age. Also, rather than working with daily counts, I computed cumulative sums which represented a user's total usage of a product feature up to a particular age of their account. Finally, since multiple users (contributors) could be associated with an account, and since this is likely to be confounded with other measures of user activity because each contributor can take actions, I divided the cumulative sums by the number of contributors. Overall, the data features that I worked with were the total usage of each product feature per contributor up to a particular day of account age. 

<!---
feature engineering
account age
cumulative sums
sum per contributor
--->
<!---
* make a figure that shows a daily feature, and it's cumulative sum. 
--->

# Exploration

Modeling 

discriminant analyses, ... 

# Modeling

LDA, QDA, ... .

regression trees, boosted trees, support vector classifier

# Results


# Conclusions

My work provided evidence against the original intuition of complex features driving user conversion. 

This lead to ... at Elastic Projects. 




