---
title: "YouTube Strategy"
author: "Mac Strelioff"
date: "`r Sys.time()`"
math: true
output:
  blogdown::html_page:
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

Here I outline ideas and strategies for growing my YouTube channel.

# General Strategies and Guides

## Meta

- schema.. an html code snippit that gives google info about a video?
- go to html code, ask dennis to do it for you... or google it lol

- playlists good for watch time -- this might be in place of a long video.. 
- videos with individual titles to funnel people in
- keyword is the the search query, er the target search query
- pick a target keyword for each video
- Youtube algo inferring search intent

## SEO

[good overview article](https://www.briggsby.com/reverse-engineering-youtube-search)

### Keywords

- keyword is the the search query, er the target search query
- Use vidiq to determine search volume potential on video keywords  
- Google search volume is not always indicative of interest in a topic on Youtube so it’s not a good idea to rely on it for choosing video keywords
- Keywords that have video carousels in the Google SERPS can increase CTR of a video and pull in more views

### Title:

- instead of 'part 1, ..' find seperate videos that can rank on their own, maybe try 'question 1' so they sound self-contained
- title case -- capitalize first letter of all words in title 
- Video is shorter than 60 characters so it isn’t cut off in the SERP
- Video contains your target keyword
- Remove excess jargon
- See SEO Framework/YouTube Distribution section - in the expanded section in middle of page - for examples.
- Do not include episode numbers for your videos that are in playlists. CTR and views might go down as episode numbers go up and the playlist is already directing the order in which your audience views so there’s no need to really include the numbers
- Briggsby found that titles with 47-48 characters perform best. This has not been reflected in our own videos so far but this is still a good target range to adhere to as a best practices.
- Front-load your keyword in your title if possible. Youtube gives more weight to words that come at the beginning of the title. Don’t do this if it comes at the expense of the flow of your title or users' understanding of your title.
- Note that your title in the video description can be different than what appears in the thumbnail (to make the title visually more succinct)

### Description

- in description, overview of everything, links of anything you want to push people to, timestamps for parts of the video. 
- longer descriptions better for ranking bc youtube, sweet spot ~350 words. 
- Include your target keyword in first line and give an overview of what topics your video will cover
- Descriptions that consist of 200-350 may to improve rankings
- Your description should not give away so much of the content of your video that people no longer need to watch to get the bulk of the information
- Link at the front, so that it isn’t cut off
- Including time stamps in your video can help prevent people who just want to understand one topic from your video from bouncing off the page when they don’t get the answers they want immediately (this is good for longer videos)

- Add summary with timecodes in the description [timecodes](https://creatoracademy.youtube.com/page/lesson/edu-discovery?cid=educational-channel&hl=en#strategies-zippy-link-2)

From [this blog](https://www.briggsby.com/reverse-engineering-youtube-search)
- Brief CTA for a relevant next video to drive session length and related videos.
- Subscribe CTA to help build your distribution power.
- 50 to 150 words in the description to summarize and describe your video, mentioning a broad match variation of your keyword 1 to 3 times, depending on length.
- List additional videos to watch, focused on your best content about the same or a similar subject matter as this video, creating recommendation clusters.
- A brief bio and/or list of social accounts, which can help build your distribution power.
- Avoid exceeding 400 words without a good reason to do so, because stuffing or going broadly off topic can harm performance.

### Tags

- Look at "view page source" and find their keywords. 
- type key words in youtube search, and add the things that it suggests.
- 1) keyword
- 2) long tail keywords
- 2-3 broadest category ones
- focus on 6-8 tags

- Include 6-8 tags
- Use this formula: 1st tag - target keyword, 2nd + 3rd tags - synonyms for your target keyword, 4th + 5th tags - related long tail keywords, 6th + 7th keywords - broad categories that your video fits into
- Use 'page inspector' option in Chrome to look up keywords used in high traffic videos on related topics! This increases your chances of being placed as a suggested video for that video


### Higher Ranking

Good advice from [joma here](https://www.youtube.com/watch?v=xdcG1M6dy58)

video guidelines for higher ranking: 

- add 5-10s pauses to let users try the problems on their own (and to increase view time)
- ask users to subscribe
- sell likes and subscriptions:
- "As you can imagine, it takes a lot of time and effort to make these videos. If you found this content helpful at all, please click the like button to let me know. Also, if there are interview questions that you've gotten, or concepts you would like an explanation on, feel free to comment below so that I know which videos to prioritize in the future. Finally, if you want to stay up to date on interview walkthroughs for common and recent interview questions, then click subscribe to stay on top of the latest interview topics."
- "Unfortunately, interviews are largely luck in terms of whether you've seen the question before. 
- In this series I walk through problems that reflect those that are currently being asked in data scientist interviews at highly competitive companies. 
- After watching these interview question walkthroughs, you'll be able to confidently brease through your technical interviews.
- Many resources, can be overwhelming and ultimately a waste of time because much of that material won't ever come up.
- My goal is to make these videos the highest return on your time by focusing on content that my friends and I have seen in interviews.

## CTR 

### Thumbnails 

[guide here](https://www.tubefilter.com/2014/06/19/youtube-thumbnails-definitive-guide/)

1. Face in a small frame over written math
2. Face large, with text formulas around it

For a background photo, choose something with blues, greens, and high contrast, and maybe face shapes e.g. search: blue green smoke black background face

- From Jessica:
- Use bold text that can be read in a variety of different sizes
- Use high resolution pictures
- Use colors that contrast against the Youtube website color scheme of red and white
- Yellow, green, orange, purple pink and blue
- Use high contrast photos
- Many experts recommend including people/faces in thumbnails to increase CTR. However, we tried this with the Kanban series and did not see CTR increase so the jury is out.

- Find a high contrast background, and maybe in ppt, put a title in white font on a black box in the center?

### Brand Consistency


## Within Videos

### Duration

- Do an incognito tab search in Youtube for your target keyword and note the average duration of the top three videos. This should give you a good idea of an appropriate duration for the type of content you’re creating
- Videos should be at least 4:30 long
- According to Briggsby: The average duration of videos that rank in the top 5 is 11 minutes and 44 seconds, and there appears to be a positive relationship between video length and rank performance. 
- Audiences also tend to “like” videos more that are in the 10-16 minute range
- However, keep in mind that you should tailor your video duration to be appropriate for the type of content you are creating and that’s why you should always be sure to note how long the videos are that are ranking for your target keyword

### Hook and Intro

1. Context: "This video is part of a series where I work though common and current Data Science interview questions. If you'd like to see more, feel free to like so that I know the these videos are having an impact, and to subscribe if you want to see the latest videos."
2. [Credibility](https://creatoracademy.youtube.com/page/lesson/edu-video-formats?cid=educational-channel&hl=en#strategies-zippy-link-2) "I have a PhD in Cognitive Science and a Masters in Statistics, currently a fellow in a sillicon valley data science bootcamp, where I'm actively interviewing, and networking with data scientists who conduct interviews."
3. Need / Value: "I realized other content sucks, and this is the best use of your time."
4. Legitimacy: "This is a question that I got from an interview" 

- start with an overview of the video. 
- start with what they want for the hook -- then ask to like/subscribe at the end for the people that obviously like. 

- Hook your audience in the first 10 seconds but don’t give away the answer to the central question of the video  that early or your audience will bounce
- You shouldn’t string them along for too long because you want your video to get to the point, but you don’t want to lose them within the first 10 seconds

- Playlists can help increase the amount of time that your viewers stay on Youtube and, in turn, improve your rankings
- However, be sure that you keep your playlists focused around one highly-specific topic. If you switch up the topic too much, we see high drop-off and videos end up looking ineffective to the Youtube algorithm.
- Additionally, if you’re creating a playlist, make sure that videos can stand alone as well within the context of the playlist.
- If they’re ranking for a standalone keyword, they won’t always appear within the context of your video and you don’t want people to bounce because they feel like they need to have watched 4 or 5 previous videos in order to understand the one that they landed on
- Writing a script is highly recommended.
- By sharing your script and refining your opening, you avoid the risk of shooting footage without a clear, strong opening

### Content

- biggest spikes are when there's new visual information.. 

- Mention emotions and feelings through a video "At this point you feel like you're doing well, then ... "
- Speak in a desirable way -- engaging or calm.
- Emphasize value of the content at every step. 
- Pause for them to try and also to increase view time metric

### End Screen

[Some advice from YouTube](https://support.google.com/youtube/answer/6388789?hl=en)

- Create a custom end screen with bold text to clearly indicate your calls to action
- Next video to watch and subscriber buttons are good ones
- If possible have your end screen pop up on the side while your video is still going on, instead of coming on against a static screen. According to Youtube expert Tim Schmoyer, this can increase engagement and prevent people from clicking away from your video
- Focus on your two most important call to actions instead of bombarding your viewers with too many options
- Make sure to hold your “subscribe” element in your end screen (see end screen example here) for at least 5 seconds before cutting away.

### General tips

- Crop out the time that I spend writing -- From analytics, long periods of writing seem to hurt user retention. 
- Instead, write everything out (maybe in a slightly vague way), and then spend time explaining the terms. 


# Planned Videos

## "About Me" Channel Video

Behavioral, "Tell me about yourself": 

About Me: 

- PhD.. , masters in statistics (borrow from cover letters?)
- Through grad school I pursued any project that was interesting to me -- It was my time to develop valuable skills and learn what I wanted to do.
- fast list of projects (decision making, prediction markets, statistics, AI and models of the mind, ... )
- relate to this job at this company
- talk about YouTube channel and growth strategy
- demonstrate the value that I add to produce positions
- decision making, so studying people and the patterns or experiences that shape their behavior
- Amazed to learn that there's a huge interplay between psychology and computer science -- reinforcement learning Skinner in the 30's, turned into a plethora of models in computer science, which are now being used to explain human behavior, and neural correlates of key values in those models are being discovered. 
- Overall I was more interested in naturally occurring datasets, and experimental design -- how we structude and verify our beliefs, and then use those beliefs to guide our actions. 
- So here at X that might look like using naturally occurring user data to develop and validate models that inform choices about product design. 

- My mission is to break down barriers, mainly by democratizing education. 
- About me: UCI, recorded lectures for students, stats masters, data scientist, ... 
- About this channel: I'll primarily use this channel to publish educational resources on statistics and programming, mainly for aspiring data scientists. I'll also use this channel as a platform to discuss hobby projects related to data science. 

## Behavioral question series

Make videos based on the questions / resources from Lacy
..

## Data Science Interview Walkthrough Series

I realized there was a lot of material to help prepare for software engineering videos, but very little for data scientist interviews. So I'm compiling videos of interview questions my firends and I have been asked in data sicence interviews, and questions that I've gotten from data scientists who are currently interviewing.

- Target Audience: People who want to know more about data scientist interviews
- Marketing: Post on Facebook, LinkedIn data science interest groups

- Value: My authority: Do an 'about me' video where I talk about my work at UCI, masters degree in statistics.
- Value: To make these videos the mose valuable use of your time, I'm focusing exclusively on questions and content that have come up during interviews.

### "Data Scientist Interview Walkthrough: Intro"

- When I was studying to be a data scientist, I realized that there were lots of resources with loads of material that won't actually help in an interview because they were too vague or too theoretical, or just contained very little material that actually comes up in an interview.
- I also noticed that there are plenty of walkthroughs for the problems that come up in software engineering interviews, but nothing like that for data science interviews. 
- So with this series, I'm creating videos that will walk you through the questions that are currently coming up in silicone valley data scientist interviews
- To make this the most valuable use of your time, I'll be walking through questions that have come up in my interviews, or in my friends interviews, as well as questions that I gotten from data scientists and product managers who are actively interviewing. 
- This way these videos are going to be the most relevant and helpful resource for you if you want to learn what it takes to excel in a data science interview.
- So.. what are these videos? 
- Each video will start with a question. I'd recommend pausing the video and trying the question yourself for a few minutes, and then watching my walkthrough for the question. 
- As I walk through the questions, I'll mention the concepts that the questions are testing for so that you can note them and dive into those later. 
- Now, some of the best questions start easy and become progressively harder, so what that means here is that, if you don't watch to the end then you might miss surprises that an interviewer can throw at you,
- that the people who aren't watching my videos won't be expecting. 
- So for now, I would recommend watching the videos, trying the problems, and seeing how I walkthrough solutions, and watching through the end so that there aren't any unexpected surprises
- If you find this helpful or interesting, like this video so that I know that the work I put into this series is having a good impact for you and other people
- Also, if there are questions that you have encountered and want answered, comment them below so that I can get you a walkthrough!
- And finally be sure to subscribe if you want access to the most recent walkthroughs
- Thank you, and I hope you enjoy these videos! 

### Data Scientist Interview Walkthrough: Probability, Part 1

- Coins in a bag
- Probability rules
- Bayes' Theorem, Bayes Factor
- Frequentist Hypothesis Testing
- Likelihood Ratio

### Data Scientist Interview Walkthrough: Probability, Part 2

Geometric distribution problem.

- This video is part of a series where I work though common and current Data Science interview questions. 
- Subscribe if you want to see the latest videos.
- And if this sounds interesting or helpful, give this video a like so that I know the these videos are having an impact, 

- This question was adapted from a question that a friend was asked during a data science interview at a large company. It's a great question because it starts out not too difficult. 
- Depending on how quickly and confidently you answer it, you get to unlock more and more challenging follow up questions.
- This question has some good follow ups that I'll reveal in this video, and at least two really great follow ups that I'll show in future videos.
- So, here it is...

- This problem starts out relatively easy but can transform into something that would be challenging to people who don't watch my videos. 
- Some people might answer a question incorrectly, and feel like it was an easy question only to know that there were 2-3 progressively harder questions that the interviewer never got to. 


<!---
todo:

- You are trapped in a room with three doors, one adds a day, another adds two days, the third is an escape. How long are you expected to be trapped in this room. 
- alternatively;
- You are playing a card game with three cards -- a '1', a '2', and an 'X'. 
- On each round, you pick one randomly. If you pick a '1', then the game continues. If you pick the 'x' then the game ends. 
- How many rounds are your expected to play?
-- Now instead there is a '1', a '2', and an 'X'. If you draw the '1', you win $1, if you draw the '2' you win $2, and if you draw the 'X' then the game ends. How much are you expected to win?

-- Now instead of winnings, the numbers on the card represent how many more rounds you'll need to play. What is the probability of the game ending? (version of Aman's question)
- Aman's question - sample from a circle using a random number generator
  - solution 1, ineffective is rejection sampling, sample from a square, then only accept samples within the circle
  - circle question from Google

-- google question: Now there are cards 1 through 6. If the number of rounds is limited, and you only win the amount you received on the most recent round, what is your expected payoff as a function of the number of total rounds allowed?
- expected value of the dice game process (get what you roll, expected value of game when you're alowed to roll n times)

-- recursive question: 
-- Now the game ends if you 

- Bank teller problem 
- random number generator from a uniform random number generator
- estimate median from Google
- variances of different experiment designs
- multinomial and guessers 'favorite color' and a proportion of users who guess randomly
- bandits vs A/B tests, particularly for lots of conditions
- LI: android you can randomize, iphone you can't (synthetic control)
- strengths & weaknesses of different ML algorithms (complex to simple explanations)
- Chris Alborn's demos?
--->

## How I Get Free Bitcoin With This Simple Python Script (And you can too!)

- can make video, then make it public later.. (after job searching ends)

- Video on my script for clicking the roll button on freebitco.com
- Simplify the script to be a python script that can be run from the terminal with one command. 
- In the video, show people how to download the script from my GitHub and run the script from terminal :D
- Add referral code so that I get a cut of the coins generated by anyone watching my video

- CTR:
- Thumbnail: Colorful background, with me looking and pointing at a screenshot of the python scrip & maybe text that says free on it?

- Advertising: 
- "Sharing this video is like giving your friends free money!"
- Incentivize: The more people who consistently do this, the more of the referral bonous I'll give back. 
- Show an example of how much I could give back if they run this consistently. 
- My goal is to make a certain amount each week, so I'll modify the referral bonus kickbacks based on that. 
- So share this video to increase your kickback. 

## What is a Power Analysis? (Explained at 3 levels of difficulty)

- Explain a power analysis (start complicated, get simple to keep people watching till the end)

1. an analysis done to find a sample size
2. formula based on t-distribution example
3. formula based on P(..)
4. General definition and power functions


## A/B testing versus bandits


# Probability Distributions Series

- Pick common distributions, describe them from the Wikipedia page
- Show their probability functions
- Show (derive?) their CDF 
- Derive their MGFs
- Derive score and Fisher Information
- Describe / show conjugacy properties?

# ML algorithm series

- Explanations, intuitions of different ML algorithms
- Strengths and weaknesses of different ML algorithms

<!--

Vevo

Chris:
- how would you interpret / recommend changes to a photo for eg nike?
- slide on nike example: most of their images are low ... ? So you're saying some of these could be
- What about the photos that are closer to the center? 


Gina:

- how do you normalize what one teacher considerd yellow versus another teacher?
- - so there's a possibility that the K means diagram would be different if this was accounrted for?
- talk more about predictions? .. About teacher alerts?
- did you try other clustering algorithms?
- 



Magna: 
- what if you wanted the best of both worlds


Misha:
- did you try adding avg cost on amazon as a feature?
- did you try other algos for class imbalance? 
- how did you handle key words? 


Pam:

- houw would you incorporate time?
- did you account for bias in strave -- so runs in french quarter might be marathons when it is safe
- how would you correct for that in your model?


Sam: 
- your approach versus collaborative filtering? 


Vy:
- what were the recommended for you?
- if you had more time, what would you add?
- how did you validate?
- 

Xuntao;

- on validation slide, what exactly do you mean by good?
- 

upcoming projects; 
- scounting algorithm to find upcoming artists and signs them!


- agency over YT recommendations? 
- lots of experimentation on optimizing end screens -- Work that Laura dows.
- - 
- greenfield: 
- brownfield: work in confounds of existing product
- DS projects combination of personal interest / quick return for work. 
- couple of projects in the pipeline, what's your interest? 
- timeline on projects, bc DS with too much time goes outside realm of value to a business
- Timeline of project negotiated with lead. 
- 


- agency in the artists / videos you promote? 



- has a data engineer.. 
- most of data coming from youtube reporting or analytics APIs? 
- also datasets with financial records
- softer measures coming out of external clients.. 


- what was your career path / background? 


- other offices in NY, LM, .. LA office focused on talent acquisition. 
- Expect to be at NY office. 
- Eng team in Portland.
- supports personal growth, sends DS to conferences, .. 


- lots of promotion done manually from content team
- future work to put measurements on it and optimize


- company mission: increase monetization of all music. Work with artist to monetize their work. 

- big 5 -- suck oxygen out of other social platforms. 
- instead, partnet with google.. 
- how do we build the tools to succeed on whatever platform we are in? 
- focus on understanding what makes an artist successful. 
- 


- DS head, started as an engineer
- 10 years in aerospace
- sr DS at playstation, focusing on gameplay
- switched to cybersecurity
- came to Vevo

- later in process: why do you want to work for us? 
- what does it mean to optimize processes for the artist? For the label? For vevo? 


- next step: onsite, 4-5 people
- one technical, python or SQL
- one softe DS making sure you understand taking a business outline and turn it into a DS problem and solution
- bus opps
- product
- other business units asking questions about the mission of the company, working through a hypothetical problem.

5 people, half hour each, plus lunch. 


-->































