---
title: "Behavioral Interviewing"
author: "Mac Strelioff"
date: "`r Sys.time()`"
math: true
output:
  blogdown::html_page:
    toc: true
    toc_depth: 4
menu:
  InsightStudying:
    parent: Foundations
    weight: 99
linktitle: Behavioral Interviewing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(entropy)

# set seed for reproducability
set.seed(10201991)
```

<!--
Try: 

- bring a notebook and use that instead of the whiteboard. -- keeps seeting closer / more engaging, also keeps a log of what was covered in the interview.

In my personal life, I manage a YouTube channel. Recently I've pulled my viewer data from the YouTube API and found that my viewers are most engaged Sunday-Tuesday. I'm acting on this insight by scheduling my videos for release on Sundays.

-->

<!---
Decent cover letter:
Wealthfront's vision of automating personal finance is very exciting to me. I have been personally interested in investing since I was 16 years old, actively trading since I was 18 years old, and I've recently been learning about automated trading and portfolio management particularly for income investing. 

In addition to the vision, the job requirements align with the tasks that I like the most within the realm of data science. I'm deeply interested in experimentation, analytics, and data-driven decision making. Throughout my PhD in an experimental psychology lab, my interest in optimizing experimental designs and conclusions drove me to pursue a concurrent MS in Statistics and to peruse the literature on topics like methods for valid inference with optional stopping. I also use analytics to guide decisions in my personal life. As a recent example, I've pulled viewership data for my channel from YouTube's API and found that my viewers are more engaged early in the week -- this guided a decision to schedule videos for release on Sundays. 

Overall I'm excited by the vision of automating swaths of personal finance to optimize passive income, and have applied many of the relevant skills through my research and in my personal life.

I hope you are interested in the skills and projects outlined in my resume, and I look forward to hearing from you if you think I could add value to the team!
--->

# Principles

- Interviews are conversations, not tests
- Use stories to establish a connection and demonstrate fit for a role and company

Tell me about yourself, your academic research, why data science?; 30 second elevator pitch vs. 2 minute phone screen/on-site

Why this company? what value can you add? Tell me about a time when… 

STAR chart (Situation, Task, Action, Result)

Mock interviews: Practice, practice, practice 

# Common Behavioral Questions

## "Tell me a little about your background."

This question gives an opportunity to demonstrate clear communication, curiosity, enthusiasm, transferrable skills, and value adds. This is also an opportunity to align past experience with the current job opportunity.

Why is it asked?

- To assess presentation skills; clear, professional, charismatic, likable, impressive

Goals of this: 

1. Impress them
2. Highlight what you can contribute (stories related to what they want)

Note -- As you answer, they are imagining working with you. 

Why should you care?

- First impressions are powerful. If you bore or annoy them, they may not be as focused throughout the rest of your interview. 


Why they ask:

- Want to know what you consider important in your background
- Want to see presentation skills
- Want to know what it will be like to work with you
- Large part of jobs is meetings and working on teams

Bonus: 'personally' ... .

Goal: 

1. Current role, background, ambitions and fit
3. Relevant experience, methodologies, and results
2. Problem, curiosity, value, project
4. key achievements, relevant to job, demonstrate qhy you are qualified. 
5. chrisma
6. proof of performance
7. Start a conversation
8. Coherence 
9. Entertaining
10. focused, concise, top selling points
11. personality
12. interest in oppertunity
12. natural
13. spontanious
14. not stiff -- 'real you'
15. comfort speaking
16. confident, compelling
11. enthusasiasm for the position
12. show you'll represent company professionally
13. charismatic and likable
14. speak smoothly
15. nervous
16. impressiveness / leadership
17. communication, language
18. tell a professional work story
19. engaging
20. compelling
21. clear
22. complete
23. create connection
24. create conversation
25. relate to job description -- issue: often times the job description is vague or unaligned with the job..


Content: 

1. Current role
2. background
3. ambition and goals
4. relevant experience
5. methods used / skills
6. results
7. why you're qualified -- impressive, interesting experience
8. key accomplishments
9. proof of performance (not summary of job duties, unique things you did)
10. accomplishments, competencies
11. what you want: this position really excites me
12. powerpoint presentation with background and results
13. company name
14. title
15. number of years
16. job responsibilities
17. mini work snapshots for every position
18. achievement oriented
19. accomplishment: anything that saved time, money, profitibility, quantifyable results
20. what you know about the role. 
21. why you are right fit: "overall ... I am confident I'd be able to succeed because..."


My Perspective: 

- What is an interviewer thinking when they ask this? 
- They are imagining themselves working with you. Do you do cool things? Do you do relevant things? 
- The behavioral and technical questions help to get a complete picture of what it would be like to work with you. 
- Will you make life easier or harder, ... ?
- Instead of making it relevant to the particular job description, make it relevnat to qualities you'd like in a colleague, and mention that explicately: "I like to dive into new things and figure them out. So during my PhD I worked on a variety of projects ... ."

Example Answer; 

- Current role: "I'm currently a Fellow at Insight Data Science. During this, I worked on a consulting project 
Overall my client was really happy with my work."
- Background: "Prior to Insight, I ... . I hold a PhD in Cognitive Science from an experimental psychology lab, and a masters in statistics. "
- Ambitions: 

Template: 

- Problem: Concepts and context
- Curiosity: Open question
- Value: Why should people care
- Project Outline: Methods, results

Example answer: 

- Open: I recently graduated from UC Irvine, where I studied statistics and cognitive science. I worked on a few lines of research, the one that was most interesting to me came out of an interest in prediction markets and arbitrage.
- Problem: So prediction markets are a platform where people can buy and sell contracts on events that pay a dollar if the event occurs and nothing if it doesn't occur. So for example, one market might be Who will win the 2020 election, and contracts might be 'Bernie Sanders', 'Andrew Yang', 'Donnald Trump', ... . Since the contracts pay out $1, the theory is that the price should estimate the underlying probability of the event occuring. And since the market is aggregating information across individuals, it should be a pretty good estimate. However, individuals have shown a number of biases in probabilistic reasoning in lab studies, so I was wondering if these same biases would exist in prediction market prices. If they did, then I could make profitable trading algorithms. 
- So I partnered with a large online prediction market to get access to their data, and found evidence of some biases consistent with those observed in lab studies. 
- Trajectory: Overall, I realized that I enjoy these kinds of impactful analyses of real-world data, moreso than theory building through laboratory studies, so I decided to bridge into a career in data science, and joined Insight to become part of a network of data scientists. 

Evaluation:

- Communication: Clearly explain prediction market mechanics.
- Enthusasism: Interest in markets and complex problems. 
- Transferrable skills: Mention some of the models used.
- Value adds: Realized prediction markets are biased close to expiration -- their signal is weaker than previously thought. Also able to profit literally by rolling out trading algorithms. 


### Child bandits: 

Bandit tasks are a common paradigm for studying individual level decision making and making claims about the way people make decisions. But in lots of contexts, the results you get when you addregate over trials can be different from the actual result on any trial. So I developed a model to infer on a trial by trial level, what decision making strategy kids were using to choose between two 'bandits' that gave out stickers. -- I have an interest in using more customized models and Bayesian inference to overcome issues that arise from aggregating data at too high a level. If you had averaged over trials, then there may have been evidence for one or another model, but the dynamic changes in decision making strategies would have gone unnoticed. 

- Similar approaches could be useful for dynamic experimental designs, OR in the context of Netflix, for personalization. If we could dynamically infer something like the strategy or emotional state of a user, then we could use that inference to personalize our recommended content or things like cover art or other aesthetic aspects of Netflix. 


## "Tell me about the project you worked on at Insight."

This question gives an opportunity to demonstrate what you'll be capable of on Day 1.

Template: 

- Open: At Insight I worked on a consulting project for an external company. This company acquired users by offering a free trial, after which users would subscribe.
- Purpose: Goals of the project were to to 1) identify, early on, who would become a subscriber, and 2) identify how the successful users were using the product. 
- Approach: I usually think about a generative process. Here I framed the problem as a classification problem and thought about using LDA or QDA because I thought the distributions of features would be different based on the classes. 
- Methods: Later thought about other algorithms because this was primarily a prediction problem, and because the assumption of normally distributed features was violated. So I tried tree-based algorithms and those performed the best across all metrics -- F1 score, accuracy, precision, and recall.
- Challenges: Non-normal features (could break LDA, QDA)

How could I have used a mixed effects model here? (See Maime's blog?)

Evaluation: 

- Clarity: 
- Relevance: Do the skills add value to the company? 
- Logic: Were sensible solutions tried in a sensible order? 

## "Why are you interested in a career as a data scientist?"

This is an opportunity to show that becoming a data sceientist at the company is the logical next career move, and to demonstrate that you know what to expect in the new role. 

Outline of topics that may resonate with a hiring manager: 

- Skills, Technical: Tools, technologies, methods you have used.
- Skills, Conceptual: Your approach to understanding problems and navigating to solutions
- Interests: What are you eager to do in this next phase of your professional life?
- Interests, Broad: Knowledge of problems tackled by data professionals in this industry
- Interests, Specific: Knowledge of technical challenges that will be faced by someone in this role
- Growth, Skills: What you’re excited to learn in the next few years
- Growth, Trajectory: Relate this job to an ultimate career trajectory

Example answer: 
When I was in my PhD, I worked on a variety of projects and realized that I most enjoyed the ones that derived some impactful analysis from larger scale data -- namely the prediction market project. 

Evaluation: 

- Educated Enthusasiam: 
- Professional Goals: 
- Niche area: 

## "Tell me about your research / talk to me about your last role."

Same as in 'tell me about your background..'

Evaluation: 

- Skills: 
- Relevance: Show how previous work relates to the responsibilities of the current role. 
- Clarity: 

## "Why are you interested in joining this company?"

This is an opportunity to demonstrate knowledge of and interest in the current role. 

Depends on deep-dive.

Evaluation: 

- Industry knowledge: 
- Company knowledge: 
- Potential for impact: 

## "Talk about a time you were on a team that struggled with effective communication." 

- Situation: Where / when did this happen? What were you working on, and with whom?
- Task: What were you responsible for? What challenges did you face? 
- Action: How did you decide the appropriate response to the situation? How did you implement it?
- Result: How do you know your solution was successful? 
- Takeaways: What did you learn from this situation? What would you do the same or differently next time?


- Can't think of one.. In community college I worked as a TA for my mentor, and I lead a research project which is very rare in community college settings. She was extremely supportive and I think communication and goals were clear across the team -- I would make outlines / agendas for team meetings. 
- At UC Davis, for my Bachelors, my mentor was really bad with email. But he was nice, and his office door was always open, so whenever I needed something I would stop by and chat. 
- At Irvine people were always available via email or even phone if needed. 
- Also I had taken a consulting class as part of the stats masters, and a portion of that emphasized the importance of clear communication with clients, so in consulting relationships I maintain clear goals and deliverables. 

Evaluation: 

- Knowledge of company values around communication: 
- Your principles for communication: 
- Awareness of problem: 
- Initiative: 
- Lessons Learned: 


## "Tell me about a time you made a mistake at work." 



- Situation: Where/when did this happen? What were you working on, and with whom?
- Task: What were you responsible for? What challenges did you face? 
- Action: How did you decide the appropriate response to the situation? How did you implement it?
- Result: How do you know your solution was successful? 
- Takeaways: What did you learn from this situation? What would you do the same or differently next time?

Forgot to add code to save a questionnaire at the end of an experiment. From that point on I ran myself and analyzed my data before running any real subjects -- so kind of like I learned the importance of unit tests from that experience. 

Evaluation: 

- Your principles for mistakes: 
- Knowledge of company values around rapid iteration, learning through failure, and troubleshooting
- Judgment: How did you explain the mistake (misunderstanding, incomplete information, technical errors)? Was it due to carelessness. 
- Responsibility: Did you make excuses, or make solutions? 
- Wisdom: Are you likely to avoid a similar mistake in the future? Can lessons here apply more broadly? 

## "Talk about a situation that required you to explain your technical work to someone outside your industry or field."


Evaluation: 

- Ability to communicate with stakeholders: 
- Impact: Understanding of what the other party needed to know
- Adaptability: Techniques (analogy, visualization, ...) used to simply communicate ideas. How did you decide what to include. Did you clarify that the explanation made sense. 
- Attitude: Will you patiently explain your ideas? 


## "Talk about a time you were asked to manage an important project." 

PredictIt proejct, since that's one that I really drove. 

Evaluation: 

- Knowledge of company values on leadership
- Trust: Why were you chosen to lead?
- Respect and responsibility: 
- Delegation: 
- People management: 
- Executive decision-making: 
- Team dynamics: 
- Potential: Strengths and weaknesses in leading.
- Interest in management roles: 


# Briefcase Document

This idea also came from [here](https://towardsdatascience.com/3-strategies-to-guarantee-a-data-science-job-with-no-experience-68d85b345f21). 

Template: 

[COMPANY NAME] Data Science Action Plan
 
Goal: 
 
Pain-Points (Speculated):
 
Project #1: 
 
Desired Outcome
 
Pain Points:
 
- pp1 
 
Proposed Experiment
 
Resource Requirements:
 
Add 3 projects as part of a deep dive. 


# Thank-You Email


### LinkedIn Thank-You Email

#### Recruiters

Hi, 

Everyone was nice and seemed to be working on interesting things!

Best,
Mac

#### First Interviewer

Hi Joonhyung,

Have you heard of [Rimeto](https://www.rimeto.com/#profiles)? It sounds very similar to the org chart product that you described during my interview on Thursday. 

I'm really excited about work across multiple teams, so I could imagine myself using such a product to meet other employees who are working on interesting projects. 



Best,
Mac


#### Gigi Zhang

Hi Gigi, 



Best,
Mac


#### Caitlyn



Hi Caitlin,

I hope you had a nice weekend. I was excited to hear a little about your work on Thursday, and wish we had more time for discussion. 

I came across some exciting papers by Jian Wang when she was at LinkedIn on what seems to be relevant work. 

Has your group published anything that I can follow up with?

All the best,
Mac




Hi Caitlin,

I thought the work on your team sounded interesting, and I would have liked to hear more about it if there had been time for discussion. 

I came across some papers by Jian Wang when she was at LinkedIn on what seems to be relevant work. 

Has your group published anything that I can follow up with?

Best,
Mac

- work focus sounded interesting
- [one paper; User Latent Preference Model for Better Downside Management in Recommender Systems](http://www.www2015.it/documents/proceedings/proceedings/p1209.pdf) is conceptually close to the approach I was trying to take for the email question.



### Yelp Thank-You Email

Hi (), 

Thank you for the interview prep information, and for helping to move the process along quickly!

I had a great time meeting the team on Friday! I also enjoyed thinking through the typical challenges that they seem to work on at Yelp.

Let me know if you need anything from me, and I look forward to hearing back about potential next steps later this week. 

Thank you,
Mac




# Cold Recruiter Email

[Blog on reaching out here](https://towardsdatascience.com/3-strategies-to-guarantee-a-data-science-job-with-no-experience-68d85b345f21). 

"Hey (Recruiter),

I know you’re really busy and you get a lot of emails. Found (Company) through angellist.  Already applied for the Data Scientist position but wanted to reach out directly! Promise this email will be < 60 seconds.
 
I’m Jeff and I’m a Data Scientist. A few things about me, I built the Data Scientist in Python & R track for dataquest.io, used by hundreds of thousands of students and by companies such as Airbnb, Spotify, Uber etc so I excel in communicating technically complex topics to nontechnical audiences. On the technical side, I built "The Booki Monster" which is a monster that eats books and summarizes them using LDA & Doc2Vec. App here(it takes a sec to load, so just be patient!) and explanation here. I also built the "Date-a Miner”, a convolutional neural network that automates online dating, by predicting the likelihood of me liking a profile and swiping for me. 
 
In addition, I’m obsessed with figuring out how to learn things fast. As a result, I’m also working on an ambitious side-project called Month to Master where I attempt to master one difficult skill each month. Skills such as going from zero to conversational in Spanish in one month, memorizing the order of a 52 deck of cards in 3 minutes, completing 27 consecutive pull-ups etc. 
 
Thanks again! I totally understand if you’re busy so no rush on reply. If you feel like there is a possible fit on your end, would love to further this conversation!
 
Hope you have a great week! Attached resume. 
 
Best,
Mac"

### Email To RobinHood recruiter

Hey Chinsin, 

I know you’re really busy and you get a lot of emails. I found the Data Scientist role at Robinhood through LinkedIn and already applied, but wanted to reach out directly! Promise this email will be < 60 seconds.

I’m Mac and I’m a Data Science Fellow at Insight. I actively trade on Robinhood and am avidly interested in democratizing access and informaiton around trading. On the technical side, I recently graduated from a PhD program in Cognitive Science and a Masters program in Statistics, where I worked on many projects related to decision making and latent decision making strategies. 

Thanks again! If you feel like there is a possible fit on your end, I would love to further this conversation!
 
Hope you have a great week! And feel free to reach out if you have any questions about my experience or interests. 
 
Best,
Mac



























