---
title: "Facebook"
author: "Mac Strelioff"
date: "`r Sys.time()`"
menu:
  InsightStudying:
    parent: Foundations
    weight: 99
math: yes
linktitle: Facebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(entropy)

# set seed for reproducability
set.seed(10201991)
```





# Onsite Prep

## Marketing metrics

Marketing specific: 

- Incrementality (lift that wouldn't have happened but for the ad) 
- CPA (cost per acquisition) 
- ROAS (return on ad spend) 
- ROI (return on investment) 
- PPC (pay per click)

One ROI formula: 

$$
\begin{aligned}
n_{leads} &: \text{Number of leads} \\
p_c &: \text{Lead to customer conversion rate} \\
\bar{s} &:\text{Average sales price per customer} \\ 
ROI &:\frac{n_{leads} p_c \bar{s} - cost}{cost}
\end{aligned}
$$

- ROI can be extended to include additional traffic, likes on social media, stronger brand (more trust, familarity, ...)

Return on an a brand campaign based on impressions or reach, cost of the campaign, and the proportion that changed their attitude ($p_{changed}$): 

$$
efficiency = \frac{Cost}{Reach*p_{changed}}
$$

[Retargeting](https://blog.hubspot.com/marketing/retargeting-campaigns-beginner-guide): Ads to a user who previously visited but did not convert

- Pixel-based retargeting: A Pixel refers to JavaScript code placed on a visitors browser (to "cookie" the browser). The cookie notifies retargeting platforms to serve specific ads. The advantage of pixel-based retargeting is that it is timely (they can be retargeted pretty immediately after leaving your site), specific to a particular page on your site, and behavior-based. Downsides to this method are that there is a lower volume of people in the campaign at any given moment in time since it's all based on how often people are coming to your website, viewing certain pages, and leaving. It also can be complicated or time-intensive to implement the JavaScript on many website pages. 
- List-based retargeting: Upload a list of emails or other identifying information to an ad server (e.g. facebook), then target ads to only those people. 


General: 

- Impressions
- Link Clicks
- Pageviews
- Deeper funnel conversions recorded via fb pixles
- Cost per click
- Post engagements on business page
- Session duration
- Pages/session
- conversion funnel

- per week
- per month


# FB Marketing Science Second Recruiter Call

Recruiter: Amber

Availability for onsite: 

- Anytime. 

Interview process:

- (done) 45min video conference with a manager
- onsite with meeting with 4-5 members on the team
- quick exploratory conversation with member of the org
- offer

- Ideally video this week, onsite nextweek, and final call next week.


Prep for onsite interview. 

- will have followup pdf of prep material
- Will meet with 4 people about 45min each
- may have a lunch as well. 
- each person has different focus area
- lunch with Elif
- Meet with Martin, Freeda, Steve, and one other (friyu?)
- Steve on ads research team as quant manager. 
- 2 technical
- 2 behaviora;
- Helen is director of org, caould possibly meet with her onsite as well. 

- Behavioral: 'tell me about a time when ...' influence and work with others, technical concepts to non technical audiences, ability to prioritize and problem solve. 
- Projects you've succeeded on. Likely ask probing questions. How you build relationships, how you present data to drive a solution
- Technical; 
- quantitative abilities, stats concepts, experimental design, p-value, correlation vs causation
- bias variance, coding/scriptiing in R/pythin
- analytical and problem solving in experimental/research design
- incrementality and causal inference
- e.g. 'design experiment needing to understand effectiveness of an image
- thinking through incrementality, CI
- focus on impact
- what makes me irreplacable in this role and how I'd apply my abilities in this role. 
- 'why I'm interested in FB and this role' 



# FB Marketing Science Phone Screen Prep

## about role: 

- product, marketing, sales departments
- create best practices for advertisers
- eg local restaurant wants to create ad on fb
- What should ad look like, where should the ad be placed, what optimization strategies should be done? 
- Not client facing. 
- Rather, collect research to generate insights for them. 

Researcher; 

- understand stakeholder needs
- turn bus questions into data qs
- develop right methodology
- work with internal partners, 
- analyze results
- communicate results through presentations, ... 

- Who are consumers of our research? 
- projects 2-3 mo. 
- 2-3 'giant' projects, and a few other underlying projects


working with internal team
- developing new recommendation
- email campaign to local restaurants for recommendations of group strategy
- recommendation package;
- right optimization
- right targeting strategy
- optimization FB uses auction mechanism
- could optimize for impressions, clicks, or conversions
- sales team thinking link click objective is best for the restaurant advertisers
- wait for a month to see impact on advertisers
- then check how advertiser spending changes
- did pre-post analyses
- sees before emails / after emails
- advertisers who saw emails increased spending relative to those that didn't see emails.


## Other Prep

Questions: 

- Do we have access to any purchasing data? 
- Do we have data post-ad-click? -- Yes from Facebook Pixels. 
- Work culture? 
- Talk a little about who my colleagues would be? Backgrounds, experience, ... ?

- meeting structures? 

- deliverable is publication -- we need to publish work papers, and the quality of them is what is judged
- have access to everyone's profiles and what they produce
- makes it good to form collaborations
- also a review board

- 2 meetings
- working on project 
- focus area meetings, different people from different organizations
- no formality about the meetings

Onboarding process 

- people they need to meet and trainings they need to keep up on. 
- onboarding buddy, many questions
- takes around 3 months to feel comfortable
- happens through reading mainly.

Glassdoor questions: 

- Please tell us about the advantages and disadvantages of our multi-touch attribution solution?
- Please tell us about your most recent experience in the workplace?
- What challenges do Facebook face in regards to measurement? 

- If you are going to work for Facebook tomorrow, what project do you want to work on?
- Why do you want to work on this project?
- Why do you think the project will be important to Facebook? 

- What if you promised work to a client for a deadline, but the data wasn't accurate. Would you send it anyway, or improve it then send it?
- Why Facebook?


### Behavioral - Experiences

Leadership: 

- Research project in undergrad
- Psych honors society + Club president, TA for Rebecca, psych tutor
- Partnership with HIP -- an Org established by Phil Zimbardo from Stanford
- Resulted in a first poster for everyone on the team, and this was a life changing experience that motivated some of us to go to continue education and even go to graduate school. 

Also; 

- Predictit Project -- Trading was a hobby with a friend
- Realized our strategies were related to psychological phenomena
- Reached out to PredictIt to get data for research
- Resulted in two posters, a trading algorithm, and more things in the pipeline (Tweet trading algo)


### Behavioral

Why this role? 

- Similar to consulting work that I enjoy. 
- Use analytics to drive decisions

Why FB? 

- Huge company. 
- Probably learning opportunities
- What I've heard of the culture -- Informal hierarchy, potential for ownership.
- Awesome research in RL (solving 6-player poker), and excited about VR and AR directions. 

1. Research areas

- Decision making
- Reinforcement learning

2. Partner and influence cross functionally

PredictIt: 

- I was interested in whether there were opportunities for arbitrage in these markets. 
- I established a data sharing partnership with a large online prediction market. 
- I involved faculty sponsors -- First Bill, then Michael. 
- I involved my friend Ryan to write web scrapers that texted us whenever an opportunity arised.
- Overall this project is a strong demonstration of by ability to forge professional cross functional relationships.

Consulting: 

UCI Ed department. 

- Dave came to us with a dataset from two courses taught different ways. 

Insight: 

- I worked with a small startup to model conversion from a free trial to a paied customer. 

TAing: 

- I taught statistics for a few years. 



- Observational methods might overestimate lift because of unassounted for competition? 
- Ads might induce a coffee craving, then the person goes to Philz instead of Starbucks. 
- Motivation can be parsed into a activational component and a directional component. Here activaitonal is like a propensity for consumption, and directional directs that propensity towards a particular brand.
- FB uniquely in a position to measure general PIT i.e. the degree to which an ad increases consumption generally, vs. specific PIT, i.e. the degree to which an ad increases consumption for a particular brand. 
- The distinction between activation and direction may not be accounted for by the observational methods. 
- In an RCT, participants in the control group may be more exposed to a competitor's ads if those were second place? So not only is lift hurt by the reduction in exposure, but also by additional exposure for the competition. 
- 


### Marketing

Campaign variables: 

- frequency (.9, 1.7, 2.2 impressions / week)
- reach
- bidding strategy
- ad placement (messenger, feed, ad column, instagram, ...)
- content (proportion video vs display image)

Some findings from [here](https://scontent-sjc3-1.xx.fbcdn.net/v/t39.2365-6/17636643_1414778175239319_70944239730556928_n.pdf?_nc_cat=107&_nc_oc=AQlLx8XaXaMhs3SHZkBNtTPhXR4PuwuVZvv6fFul1ne96lHNk0k4207_s52OMhSxWwx3WOFsGuM2ODg1Hw_0HSnG&_nc_ht=scontent-sjc3-1.xx&oh=bf63041dcee5ed850a7cfb2b1871f1ac&oe=5E510238):

- Low/medium frequency maximized ad recall
- Favorability increased by video impressions

Campaign objectives: 

- impressions and awareness, or reach (better for upper funnel goals)
- consideration
- conversions or sales
- loyalty
- timely -- content can be optimized against market trends (e.g. vacation destinations seasonally)

More from [here](https://scontent-sjc3-1.xx.fbcdn.net/v/t39.2365-6/17636643_1414778175239319_70944239730556928_n.pdf?_nc_cat=107&_nc_oc=AQlLx8XaXaMhs3SHZkBNtTPhXR4PuwuVZvv6fFul1ne96lHNk0k4207_s52OMhSxWwx3WOFsGuM2ODg1Hw_0HSnG&_nc_ht=scontent-sjc3-1.xx&oh=bf63041dcee5ed850a7cfb2b1871f1ac&oe=5E510238);
- Ad recall: Do you recall seeing an ad about ___ on ___ in the last 7 days?
- Favorability: What is your opinion of ___ overall?
- Mission perception: Facebook and Internet.org specific metric evaluating agreement with
the company mission
- Company perception: Facebook and Internet.org specific metric evaluating perception
of the company
- 50-75% video vd display ads was optimal for incremental lift (2% lift over the 25% group). 

Outcomes of FB study: 

- low frequency lift in ad recall of 1.7%, medium frequency higher incrementallity of 7.1%
- Favorability - low frequency lift of 11%, no evidence of a difference vs medium or high freq
- No lift in company perception

Advice from FB study:

- Hypothesize, test for actionable results, and act
- Define right creative mix for brand
- Learn from all results


ML recommendation for a tuned ad camapign is 50 conversions

Campaign strategies from [here](https://www.facebook.com/facebookbusiness/videos/2505731469510573/): 

- Polling ads in feed
- Playable ads
- Augmented reality ads (e.g. showing makeup on your face)


Article on incrementality [here](https://scontent-sjc3-1.xx.fbcdn.net/v/t39.8562-6/40885602_325378801543933_2786346366694064128_n.pdf/fbiq_implementing_incrementality_inline.pdf?_nc_cat=105&_nc_oc=AQkk5JjEDqEvHR8zjYomZRFBWVzVMiJ-0rmN0lg7XXVD6y8i02qe7NFuyU-GeDs4CfI5WSITVZWmDoS-8FRx6OY0&_nc_ht=scontent-sjc3-1.xx&oh=ae344a3e087c4b7322ded9a001f4949d&oe=5E5E8B86):



Article on common problems [here](https://scontent-sjc3-1.xx.fbcdn.net/v/t39.8562-6/55966733_554973988328944_5356351545606668288_n.pdf/incrementality_measurement_inline.pdf?_nc_cat=100&_nc_oc=AQla0M5gBHc5T49iCiX_UR_RCpWJQm4X5d9fanAHF22vlBpD87lQnZAKmqOm1PoU7_bhZzcF6rhyoqeD9m6lEAQ6&_nc_ht=scontent-sjc3-1.xx&oh=3ddc9c305b5e21813e2a3f1142f04e9d&oe=5E1F884D):

1. Not enough power

2. Outliers

3. Variables not isolated (multicolinearity)

4. Noncompliance

5. Engagement or novelty effects

6. Unmeasured important variables



Metrics: 

- Impressions
- Link Clicks
- Pageviews
- Deeper funnel conversions recorded via fb pixles
- Cost per click
- Post engagements on business page
- Session duration
- Pages/session
- conversion funnel

- per week
- per month

### FB metrics

- 700 million monthly FB gamers
- 


## Maime tips:

- If it's a seperate org interview is prob still similar.
- Maime didn't have a great experience with SMG group (small medium business)
- Maime's cohort they didn't get back to someone until towards the end of the year. They were on a hiring freeze.
- Maime was for incoming PhD grad role. 
- Maime tech screen; 
- half coding, half analytics, half SQL
- don't code for python algos, coding was only SQL
- In general, product/open ended, and statsy questions. Like 3 open ended and a stats session.
- very very deep dive. 
- Should be ready for an analytics problem with fb marketplace. 
- They expect you to know facebook because it's so widely known
- Get a lot of context, deep dive products, pages, news feed, events. Know them well. 
- Know how they generate revenue, what metrics they care about. 
- Should be able to rattle off like 10 metrics for whatever question.
- Especially the case for well known companies. 
- Should already know metrics, not need to brainstorm them on the spot.
- Complicated queries -- Lots of logical stuff, tricky questions. 
- Be comfortable with medium level on Leetcode and hacker rank.

In general, interviewing well -- know how to ask for help for SQL and clarificaion. Verbalize what you're stuck on and need help on. 

Draw intermediate tables. If I could get here -- I'd .. . But I'm stuck on this step 1 part. 

FB really good at accomidating schedule. Maime got onsite quickly. 
Should see it through, I might love the team or like working there. Could get a good compensation package. 
Recruiters will ask where you're interviewing, you can tell them. 

Hesitate when they ask about how much the offer is... . 


# FB Marketing science Recruiter call

[job ad](https://www.facebook.com/careers/jobs/655936761589571/)

[Similar ds job ad](https://www.facebook.com/careers/jobs/2265158820402695/)

- Recently graduated with PhD in cognitive science. 
- Research topic focused on decision making and reinforcement learning -- including studying the psychological mechanisms behind effective advertising. I also earned a MS in statistics, and recently finished the Insight Data Science Fellows program, and am looking for positions as a data scientist in the Bay Area. 

- I like the idea of working with small businesses. 

- Q: What would the day to day work look like for this position? 
- What sort of data would I have access to? .. Data from a partner company such as conversions on the small business webpages? 
- Could you give me an example of some recent projects that people in this position have worked on? 
- How does this position relate to data science roles? 

- Pinterest onsite.. expedite process?

Marketing science

- 7 teams to better serve ads clients to help them get best ROI on ads, and measure effectiveness of ads
- Share this data with the advertisers to give them new strategy ideas
- Teams intersect product and data science, and others on research. 
- Research team does a lot of experimentation, causal inferece, hypothesis testing, ... 
- Research focused on understanding user behvior, understanding why people click ads or spend time on different pages. Typically from research or economist background. 
- Have aobut 5 researchers, looking to add three more before the end of the year (1 offer out now). 
- Might add a few more next year. 
- Team centralized in Menlo park. 
- This is the SBG team. 
- Tools are Python, R, SQL, SPSS. Mostly R and Python. 

How is researcher different from DS? 
- Researcher focused more on research, hypothesis development and designing and executing measurements, and publishing results. 
- DS teams more focused on developing stats ML methodology and productionizing them as products. More model building.
- Researcher more client facing with advertisers. Work with internal ad agencies they hire who then interface with esxternal clients. 

- sample not representative of population
- eg impace of nationwide ad campaign
- only have data for UK
- only from london

Interview process

- 45min video conference with a manager
- onsite with meeting with 4-5 members on the team
- quick exploratory conversation with member of the org
- offer

- Ideally video this week, onsite nextweek, and final call next week.














