---
title: "Instacart Notes"
author: "Mac Strelioff"
date: "`r Sys.time()`"
menu:
  InsightStudying:
    parent: Foundations
    weight: 99
math: yes
linktitle: Instacart Deep Dive
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(entropy)

# set seed for reproducability
set.seed(10201991)
```


# TODO: 

- Check out info from [blog](https://medium.com/acing-ai/instacart-data-science-interview-questions-e8d89bea1a34)
- Read articles on their [DS blog](https://tech.instacart.com/tagged/data-science)
- [LinkedIn application for data scientist](https://www.linkedin.com/jobs/view/748128414/?refId=aa6b5d2c-8b03-4c2d-9643-1171a9fca283&trk=d_flagship3_company)
- [Instacart posting for data scientist](https://boards.greenhouse.io/instacart/jobs/1863911)
- [LinkedIn app for analyst](https://www.linkedin.com/jobs/view/1331659318/?refId=aa6b5d2c-8b03-4c2d-9643-1171a9fca283&trk=d_flagship3_company)

# Recruiter call

"Just be prepared to share with me what you are looking for, what is exciting to you and feel free to have questions ready about the team, role, business etc"

<!-- excitement -->

- Groceries have been hard for internet companies to get right -- it's exciting to see Instacart managing this well, and I'd be excited to be a part of this technological revolution of grocery delivery

<!-- questions -->

- More about role?
- general interview at this point, then team placement later? 
- to see what product team is best fit, then match that with their priorities
- data cleaning, kpis, models
- experimentation heavy
- DS vs ml; DS models increase understanding and guide decisions
- hiring in customer - growth, retention and engagement, marketing, core product
- and in performance - delivery logistics and operations for shoppers, fulfillment, shoppers and delivery
- - surrounding shopper model incentivized by flexibility in hours, and pay structure. 
- - competitive - they could be in postmates, doordash, ...
- - incitives, earnings, ... 
- - focused on incentivizing quality rather and balancing with speed.
- - experiment with different incentive structures.. 
- and in ads platform - cupons, product promotions (buy 1 get 1 free), ... 
- - all from brand partners
- - sales drive brand partners into business
- - DS around 10 individuals
- currently have 5 products in ads now, some tools help partners decide how to spend dollars

- Specific needs or challenges?

- Instacart growing at a pace faster than others in the bay area
- DS only 25 individuals, still one head of DS
- DS highly valuable and high ownership

- Sr contributor, prioritization important. 
- Each product team is cross functional, 1DS, 1 designer, 1-8 SWE, and a product manager. Desks are organized around these. 
- Owning metrics with the product teams. 
- E.g. earnings model might be partnering with growth team and delivery logistics side
- Report into a DS leader for mentorship, collaboration, ... .
- Still have autonomy and collaboration in day to day

- variety of team members in interview to chat about different projects
- feel free to ask about their day to day

Next steps

- problem solving phone interview (45min) - business case problem from a Sr DS, high level instacart related problem. E.g. how would we gain more customers, retain more customers. Something you'd think of as a DS. ask insightful questions, setup framework correctly, back up analysis and solution over phone. Looking how you organize thoughts and pivot thinking, might have a wrench thrown. 
- statistics SQL phone interview (45min). Stats 101, SQL is a necessity so quick 15 min exercise should be straightforward. 
-- coding over shared doc? 
- - no, first 30min over phone, next 30min online through a link 
- Onsite interview with a lot of topics. Experimental design, live DS project with clean data. Want to see how I solve it and present answers. Multiple ways of answering prompt. 
- project in three sessions; 
- 1 framework and metrics, 2 doing the work, 3 presentation to team of DS, strengths and weaknesses and justification of choices
- experimental design, problem solving/product sense

- hiring leader on customers will be out of office starting October 7th 

- will be asked about compensition at onsite.
- DS, Sr DS, Staff DS -- depends on interviews, and determines pay range. Will get cash based and equity in RSUs and then benefits. 
- Sr range between 170-190k on cash. Look at technical contributions, level of inititive, thought leadership, 400-600k over 4 years of equity. 

# Problem solving phone interview (45min)

- business case problem from a Sr DS, high level instacart related problem. 
- E.g. how would we gain more customers, retain more customers. 
- Something you'd think of as a DS. 
- ask insightful questions, 
- setup framework correctly, 
- back up analysis and solution over phone
- Looking how you organize thoughts and pivot thinking, might have a wrench thrown. 

- 'How do we get more customers?'
- referral bonuses, ads, ads + discount codes

- increase customers
- retain customers

<!-- Possible topics -->

- Improve predictability for shopper experience
- Inventory prediction or modeling
- Model for item substitutes (crowd source this so that orderers can specify acceptable substitutes?)
- Labor models in local areas, accounting for unions and labor laws
- Trust with person delivering produce

<!-- Insight Mock Qs -->

- Instacart (a grocery delivery app) implemented a pickup option at a subset of grocery stores that partner with the company. The subset of grocery stores that got the pickup option was not randomly assigned. How would you figure out whether the revenue from pickup is incremental to delivery? In other words, is pickup cannibalizing delivery?

- At Instacart, if you order 1-7 items, the delivery window is 1 hour. If you order 8-24 items, the window is 2 hours. If you order 25+ items, the window is 4 hours. Why is this approach problematic?

- Imagine Instacart is rolling out a program which allows grocery stores to reduce wait times for pickups. Design an experiment for this program. 


- Brett 
- fulfillment side: shopper success

- Customer side has ads, growth, and core
- bus
- falls under customers catelogue team


## From video on hiring practices

- objective, assumptions, scope
- reliable, readable, flexible
- logically sound and complete
- clear description of work and sharp Q&A


# Technical Phone Interview

Interviewer: [Gregory Renner](https://www.linkedin.com/in/gregxrenner/)

- Growth team
- Started on people analytics team
- Previously: Airforce, stats teacher, optimization and operations research


## Stats: 




## SQL:





### Framework 

- Instacart delivers groceries online and on app

- online - cookie assignment issue.. 

- assume people order all groceries from one shop
- Instacart dispatches shoppers to fulfill order
- shoppers (picker+delivery) or picker and deliverer
- customers fill out their cart, then see available delivery times
- times in blocks of an hour
- marketplace involves stores who give catelogues and sometimes pay
- and goods companies place ads in app to have product come up

- aim to deliver asap, don't always have enough shoppers to meet demand. 
- Turn off timeslot if unavailable
- lets say we have busy pricing to combat this, so just charge more instead of turning slot off
- can increase up to 4x, usually just by a few dollars
- 

- Goals: how would you know if surege pricing is a good idea? What next? 
- Metrics: 
- - moving demand?
- see regular prices as baseline
- see surge prices
- - higher revenue?

- Interventions
- Incentives for each stakeholder (what if we optimize for this)
- Models: assumptions, estimators

### Metrics:

many from [this presentation](https://www.slideshare.net/JagannathPutrevu/supply-optimization-instacartslideshare)

note when looking at product in video

- efficiency = delivery time / active time \* active time / total time = active efficiency \* utilization

Shoppers: 

- Driving time: batching, proximity to store, traffic
- Picking time: speed of shopper, shopping list ordering, checkout times
- Bags pickup time: staging area layout, numeber of bags being picked up
- Delivery time: Traffic, order time/space density, routing algorithm efficiency
- Idle time: Supply/Demand equilibrium, variance in cancellations, variance in shifts

Process: 

- Demand forecasts
- Space/time density
- Store Locations
- Shopper pool or staffing
- Traffic
- Weather
- Shopper ability (speed, precision)
- Fulfillment times
- Cancellation probability

Constraints: 

- handoff vs full-service
- idleness vs efficiency vs lost delivery
- store timings
- shift length requirement
- business rules

Costs:

- idle hours
- lost deliveries
- lost efficiency

Outputs:

- number of shoppers required
- percent of volume done through handoff
- estimated efficiency and utilization

### Complications

For ad experiments;

- Users go on vacation, (W=1,T=0,Y=0)
- Competition bids more
- Ad targeting biases sample
- Algorithms for routing shoppers can't be tested within the same geography since routes for T shoppers would influence the routes for C shoppers

## My Value ads

- [personalization](https://blog.dominodatalab.com/data-science-instacart/) mentioned at 31:00 in this video. 
- My research on utility-based decision making, and on RL and learning about environments to optimize decision making could both contribute here? 
- My work on inferring what strategy a person is following could relate to inferring their utility functions?
- My work on dynamic logistic bayesian regression could offer a fast way to approximate utility functions for different users, since random utility models are similar in functional form to logistic regressions

Ads: 

- Motivation has two components: activation and direction. 
- Activation: I'm not really hungry, then I see sizzling bacon and that makes me hungry. 
- Directing: I want bacon, then I see a nice omlette and decide to get that instead. Changes the action that manifests out of the latent state. 

- From YouTube, you can advertize to viewers who watch competing channels, e.g. I'd advertize on Ben Lambert since he also has educational stats videos. 
- At Instacart, this means advertizing to customers who are searching for a substitute product.. 

- Using substitutes and complements
- Advertize to users who are searching for a substiture item (eggs from a different farm)
- Advertize to users who are searching for a complement item (eggs for someone searching bacon)
- Bigger issue -- an ad to someone who is going to buy the product anyway is wasted money.. 
- Ads should target people who would buy if they see the ad, and wouldn't if they don't.
- Showing ads to people who will buy anyway confounds the effectiveness of the ad experiments. 

### Discussion of past work
"Be prepared to discuss your past work involving analyzing large and complicated datasets, defending your approaches and communicating what you learned during your project."

"elaborate on related projects from your resume"

PredictIt Project:

- Situation: 
- Project: 
- Maybe sketch the fig of price for Trump win versus Republican win
- I also aggregated data based on days until expiration, and applied a linear in log odds model at each day. 
- Found the common S shaped calibration curve that comes up in lab experiments, particularly at 1-2 days before market expiration.
- Result: 
- Value to Yelp: Relates to the economic patterns maybe? 

Strategy Inference Project:

- Situation: 
- Project: 
- Children and adults might use different strategies when making decisions. 
- I worked with a friend to formalize the possible set of strategies, and then I implemented a model to infer the probability of a kid following each strategy on each trial, and applied Bayes Theorem to get a probability that the kid was following any strategy over time. 
- Result: A lot of experiments focus on which strategy best fits all data across trials -- the approach that I took allows for changes in strategies, and the exciting result was an ability to track latent decision making strategies over time. 
- Value to Yelp: At yelp, for example, a user might be choosing restaurants based primarily on value, then shift to preferring restaurants based on rating. An analogous modeling approach might be able to detect, in near real time, the features that are driving an individual user's decisions. This informaiton could then be used to modify search rankings. 
- More specifically, model click probability as a function of value and stars, estimate the coefficients online, and use the coefficients to prioritize these features in rankings. 

General interest in decision making: 

- Situation: Models of multi-alternative decision making are often applied to food preferences to see how people integrate information about price, healthyness, flavor, ... . 
- Excitement: Yelp is basically a giant experiment in multiattribute decision making. 
- Value to Yelp: Theoretical insights might help in guiding how restaurant informaiton is displayed to consumers. 

Insight Project: 

- User funnel and user flow, maybe should have started at these simpler analyses
- Learned lots about decision trees, random forests versus gradient boosting and gini impurity versus mean decreas in accuracy
- Chose gini impurity because mean decrease in accuracy labels collinear features as unimportant
- Chose random forests because it does a better job of pulling out important collinear features

# Deep Dive

## Business Model, Culture, and Vision

Business model:

- Instacart brings groceries online, through stores rather than through fulfillment centers (e.g. how Amazon does it).
- Recently showed their model was profitable and sustainable
- Became economical by batching orders, taking advantage of economies of scale, ...
- Gross margin positive, implying growth will be profitable
- Tips can only go to the last person that touched order (delivery) even if they didn't put together the order (pickers). 
- Brings incremental volume to grocery retailers
- Around 50/% of grocers have same price on app as in store, others have markups
- Seen as a antidote to Amazon by supporting local business
- There's a grocerie store within 10-15min from every household
- Most valuable ads because they influence behavior right before the purchase
- Want to build AdWords for groceries

Delivery Models;

- Handoff model: in-store pickers fulfill orders and stage groceries for pickup, drivers pickup groceries and deliver them
- Full service: a single shopper picks and delivers

Revenue

- Subscription or delivery fee from cusomter
- Service fee partially goes towards balancing tips for delivery and picking. 
- fee from retailer
- revenue from advertisers (talked about around 29:00)
- coupons 

costs

- delivery costs, pickers and delivery (can be different people)
- credit card transaction fees

I like the impact that data scientists can have:

- Minutes saved in deliveries is /$0.25 in gross margin, which can be passed to savings for the customer

I like the enturpneural spirit: 

- 6 months after Amazon bought Wholefoods, Instacart signed partnerships with nearly every large retailer 

## Projects, Tasks, and Data

Open problems:

- Improve predictability for shopper experience
- Inventory prediction or modeling
- Model for item substitutes (crowd source this so that orderers can specify acceptable substitutes?)
- Labor models in local areas, accounting for unions and labor laws
- Trust with person delivering produce

# Deep Dive

## Stakeholders and Use Cases

User experiences covered in the beginning of [this video](https://blog.dominodatalab.com/data-science-instacart/).

- Customer: Want to search and pick groceries for delivery, paritcularly items they are loyal to, possibly from stores that they are loyal to
- Pickers: Part time employees with hourly pay and incentive structures go to stores, find and scan items from a customer's list. 
- Delivery: Contractors with incentive based pay deliver items from picker to customer. These are contract workers 
- Stores: Want their store to be chosen by customer
- Advertisers: Want to increase demand possibly through ads

- Instacart doesn't tell shoppers where to find an item if a store is out of inventory. One reason is to maintain relationships with stores, rather than products.
- Adding other types of retailers to the platform, but don't want to canibalize the relationship with current retailers

## Metrics

Ideas from [this video](https://www.youtube.com/watch?v=-Y8GGgT4Qf8),

Customers: 

- User funnel; store search, item search, checkout, delivery screen
- Delivery page views might indicate demand
- Bounce before delivery screen might indicate browsing without intent
- Bounces at delivery screen might indicate a decision to go to the store instead of use instacart

- Browsing metrics
- Checkout metrics: can check out (convert), get to checkout screen and see no delivery times then decide to go to store on their own (lost sale), or not go to check out screen (just browsing). Neglecting the lost sales could negatively impact staffing decisions, e.g. fewer delivery slots -> fewer shoppers needed -> fewer delivery slots -> ... -> no more business.
- Log every exposure to availability
- Model probability of a checkout given customer-store-geography-hour. Then go back and model the probability of a checkout if the past customers had seen available checkouts. Demand models like this help with staffing decisions, and identifying undre staffed areas.
- Demand = p(convert | 100% supply)
- CI methods for inferring demand if there had been supply? Can compare demand in similar regions that have sufficient supply (nearly no bounces from checkout page)

Pickers: 

- time between scans on barcodes (time between picking items)

Delivery: 

- Goals: 
1 match demand to maximize conversions
2 efficiency for good unit economics
- Delays in delivery could indivate holidays, bad weather, regional traffic events


For profitable unit economics;

- More efficient deliveries; more deliveries per shopper (picker, delivery) hour
- Number of deliveries / number of labor hours
- Can improve if shoppers are better utilized (less idle) or faster (more efficient, less time spent searching for items)
- Improve operational organization
- Improve incentives and training for shoppers to reduce 
- Part time employees in store
- Contractors who deliver


## Monetization

- + delivery fees from customers
- + Service Fees and Tips from customers for shoppers
- + Product partnerships from advertisers for ads
- + Retail partners subsidize delivery to get more customers
- - transaction costs, driver insurance
- - time driving and shopping, can cost more than service fees and tips

Instacart ads are highly valuable because of opportunities to measure intent and influence behavior at the point of sale. 

## User Flows and Metrics

Thinking of the broader user flow can help with identifying measurable events within that flow (metrics).
Overall, consider units of individuals (accounts, unique visitors, cookies, IPs...), units of time (daily, weekly), and referents (week over week, ...)


From [Jeremy Stanley small talk](https://www.youtube.com/watch?v=-Y8GGgT4Qf8)

Customer Experience

- Select store
- Shop by selecting items
- Checkout
- Select delivery time
- Return

Shoppers

- Accept order
- Drive to store, get list of groceries
- Scan bar codes
- Delivery

- 'buy it again model' sorts items shown to users based on how likely it is they'll buy them again


## Data Science work

From [video](https://www.youtube.com/watch?v=-Y8GGgT4Qf8)

Forecasting demand and supply (bounces from checkout and idle shoppers)

- Different time series models perform better or worse at different times of year, so the team uses different models depending on time of year. Could this be optimized with bayesian model averaging? Or would that lag the changes in the data?
- Brain following habitual (model-free) vs goal-directed (model-based) strategies and shifts between these strategies depending on outcome variance. At instacart, a similar modeling approach that automates changes between forecasting models or models for staffing shoppers might be more efficient than a current method? 

Balancing supply and demand (changing delivery prices based on capacity)

- Charge more for delivery when estimated capacity drops
- Incentivise people to place orders where it will be most efficient by offering cheaper prices
- Account for consumers feeling gouged? 1) UX team can think about how this pricing influenced customers satisfaction, 2) AB testing, 3) models of longer term behavior of users exposed to higher surge prices to see causal effects of price strategies on longer term behavior

Fulfuillment timeliness (fulfillment speed, probability deliver on time, chance shopper gets all items, customer happiness)

- Customers happiest near the beginning of time window, either before or after beginning of time window
- Could start with Google API, but this breaks at scale
- Instacart models outperform Google API estimates
- Shoppers pick and then stage orders
- Then drivers go to stores and pick up orders, then deliver them
- Use quantile regression to model variance, which is important because of all the steps being modeled (picking each order, driver picking up each order and delivering each order)
- (XGBoost?) Gradient boosting machines for comples time and space features and for scale
- Account for picker variance? Design app to minimize picker veriance?

- cost of idle hour (know shopper hourly pay)
- cost of being late, know how much it affects customer happines, can relate to customer retention
- guard rail metrics: probability of being late, 
- Netflix heuristically doubles value of customers for network effects to account for 1 other friend
- understanding queues is crucial for efficency
- having staff that can pick or deliver enables efficency of handoff model where pickers stage orders for delivery, or can deliver themselves

Capacitized vehicle route planning with time windows: 

- computational infeasibility e.g. O orders, D deliveries, N shoppers leads to O choose D * N options
- pick subset such that orders in only one batch, orders delivered on time, shoppers move as fast as possible
- impossible problem... 
- use greedy heuristics; for each unassigned order, assign to shopper that can do fastest, find other orders they can do quickly, ... . 

Shopper efficency: 

- Shopper speed (items per minute) vs batch size (items on list)
- Control: sort departments randomly, then sort items within departments alphabetically. Shoppers got faster as batch size increases because item density increases (more adjacent items) and fewer unencountered items in unknown locations
- Human sorting: people curate the orderings
- Travling salesman solution: graph of items penalized by observed times between pickups. Ignores things like cold items parishing
- Deep learning solution: outperforms human curation and travling salesman solution at large batch sizes. 
- Problem: In a store, just pickes item a, need a model to suggest which item to pick next that would maximize efficency (RL problem with markov state space determined by which item was just picked!)
- Estimate P(next=item A | last = item B, candidates = unpicked items in list)
- Deep learning structure - embed products, shoppers, stores, account for candidate set, predict next item, penalize from cross entropy loss function
- Make predictions either for individual shopper or for best shopper at a store location
- see article on 'deep learning with emojis'
- 


Driving basket sizes: 

- important way to increase revenue


Considerations; 

- long tail, ie storing lots of items
- parishability, storing items for limited time
- timeliness, physical pickups need to be close to dropoffs
- cost
- human errors;
- pick wrong item (protected by scanning UPC code)
- flag item as not there, when it was just not found

Product Discovery

- Discovery in stores based on laying out items in a way that forces users to walk past new items
- At instacart, deep learning from image to see how similar item is to one that users may have bought


### On Web

1. Users (IPs) arrive on Yelp, can be assigned a cookie, or associated with an account if the user creates one. 

- Growth: DAU, MAU
- Growth: monthly new users, monthly unique users
- Engagement: Reviews per user per month
- Engagement: 
- Engagement: Traffic to business pages
- Monetization: Reservations
- Monetization: Waitlist

- Performance: Wait times at restaurants
- [Some metrics for business partners](https://biz.yelp.com/)

### On Mobile


## Current issues

- Supply/Demand balancing?

## Competitors

- Amazon
- Other food delivery -- Grubhub, Uber Eats, ... 

## Areas where ML is impactful:

- Machine learning is critical for our logistics teams, where we balance supply & demand and optimize the vehicle routing problem we have to fulfill grocery deliveries. We use machine learning (and operations research) to forecast distributions of outcomes, optimize control problems, predict grocery shopping and driving times, and solve routing optimization problems. We also use machine learning to assist our shoppers in stores by sorting their shopping lists.
- Another area machine learning has had a significant impact is in our catalog. We use machine learning to predict the probability any given item will be found at a given store location, and to suggest replacements for items that might not be found. There are many applications for using machine learning to improve the catalog (remove duplicates, tag products, enrich metadata, etc.), and so we are just beginning there.
- Last, but not least, we use machine learning extensively for search & discovery. I’ll let Sharath follow-on there.
- We haven’t used machine learning to affect growth (user acquisition) much. In part that’s because we have been growing so fast, we haven’t needed to optimize our growth strategies. In part it’s because we are still rapidly iterating our growth products, and so simpler solutions have been preferable.
- On the Search and Discovery side, there is search matching and ranking, merchandising across the site and several contextual recommendations including ads targeting and repurchase modeling (this competition!), which have benefitted from machine learning techniques.
- There are others such as query understanding - query expansion, spell-correction and autocomplete - where simpler data mining style approaches (aggregation, domain knowledge etc.) have been effective. This would be one of those areas where strict latency and engineering complexity raises the bar on how much more complex models must help to justify the investment (personalized query autocompletion for eg.)


## Notes on A/B testing from Jeremy

It very much depends upon the application. If we have a rigorous way of measuring the desired impact when deployed (usually an A/B test), then black-box models that maximize predictive power are often preferred. Even then, we often seek to understand those models in order to improve them, and in order to understand where they may fail in edge cases. At times, this means building a more structured model as well purely to aid understanding.

In some cases, we cannot A/B test. This can arise because of marketplace dynamics (groups of shoppers or customers are not independent) or because we are seeking to estimate something for measurement rather than for action. In these cases we prefer more structured models, as they can be interrogated and validated and their failings are more easily understood.

We also have applications where we expect the model to be used frequently outside of the domain it was trained in. This can happen when first introducing machine learning models. You begin a product with a simple set of heuristics that preclude you from ever observing a large part of the potential data space. In these cases, simpler models may generalize better to these unobserved spaces, and we can slowly build up exposure through explore / exploit approaches.

## Some exciting things about Instacart

From [why VP of DS joined](https://medium.com/@instacart/our-new-vp-of-data-science-answers-why-i-joined-instacart-2034f467577d)

- Instacart has a very unique business model, and that is why data science is so important for our success. Instacart is in part an ecommerce marketplace, and so we have all of the same fascinating catalog, search, recommendation and community opportunities that eBay and Etsy have. But Instacart is also a real-time logistics platform. So we also have all of the same fascinating forecasting, scheduling, operations and fulfillment opportunities that Uber or Lyft have.

## Ideas, excitement, questions to ask


## Glassdoor interview questions

- How to do power analysis for an A/B test.
- SQL timed exam
- Questions about efficiency curves in the supply demand distribution of Instacart's logistics.
- 1. Applied online, got a HackerRank link with SQL question. It is supposed to be completed within 2 hours, but it usually takes 30-40 minutes to solve. 
- 2. Phone screen with recruiter. It was a bit different since the recruiter didn't ask me any of my background or job fit, but rather asked me to drive the interview with my questions. She did ask some logistical questions like location, visa status, etc. 
- 3. Got a data analytics takehome assignment. Was given 2 days to accomplish it. The assignment was related to A/B tests, and exploratory data analysis. Had to prepare presentation. 
- 4. Phone Screen with Hiring Manager. Asked me about my background, ideal job and couple of open-ended questions regarding Shoppers in Instacart. 
- 5. Onsite Round 6 interviews, which constituted analytics take home presentation, analytical problem solving, statistics, culture fit interview during lunch, engineering partnership, product partnership, and with hiring manager. I liked the rigorousness of the process but was really disappointed when no feedback was given after I was rejected after the onsite.
- Without giving away the challenge I can say that I assume they were looking for more of a linear programming algorithm then the simple arithmetic I used to solve the problem. 
- SQL query and then an employee optimization dataset.
-  The most interesting part of the process was the take-home which consists of 1 ambiguous at best question with a data set of 1 month of order data, which is less data than they open-sources. 
- The HR representative said that for the 48 hour take home most people put in 4-6 hours to complete it, but because they want a visualization board, powerpoint, or presentation medium which can take a lot of work, it can feel like just another Silicon Valley rush assignment to do a full project. 
- How would you staff the team based on delivery data?
- Estimate the demand and supply
- Code challenge, hiring manager scan and then onsite. The HRs are very professional, but the interviewers are expecting you to know their business very well and they give very vague questions without enough explanation, without any guidance. There would be three technical white boarding rounds, each rounds you will deal with two data scientists. They ask questions about the business is dealing with, but no guidance, and they explain things really poorly, even one of them didn't say a word during the whole 45 min session.??????? Excuse me???? And they will tell you the result immediately, if you don't pass, all the following interviews will be cancelled.
- All HackerRank tests. An algorithm question about a kind of thing you will NEVER do at a job, and a SQL question that was reasonable and not the usual trivial thing. Phase II if you get past that or aren't age screened out yet, is analyzing a simple data set and make a presentation about your findings.
- 1. SQL test 2.Recruiter screen 3. Data take home challenge 4. Phone screen with a data scientist 5. On site Overall it was a smooth interview process. The recruiter was very helpful. The data scientists and PM's I met seemed smart but also very serious (could sense some stress). The on site has a behavioral competent (freebie if you can communicate decently) as well as several technical interviews. They will ask about statistical techniques you would use to solve a specific scenario (monte carlo simulation, decision tree, etc.). The interview was pretty rigorous and they will gauge how advanced you are with statistical knowledge and ability to apply it to business problems. Overall I thought I did well in all interviews other than a portion of one of them (didn't know what statistical method to use to solve specific case question), and ended up getting rejected.
- 1. We are observing this trend, what are possible explanations for why? 2. Behavioral (talk about a time when...) 3. SQL. Did not have live coding, only in the initial problem and take home portion
- The first interview was to send me a data set. Given a set of training cases, you need to extract the features and train a model, to predict for the test set.
- I can't reveal them but mostly around problems in Logistics that Instacart solves on a day to day basis.
- The coding challenge was a timed test mainly on predictive modeling.
- During the phone interview it was clear the interviewer had spent time looking at my past work and asked highly detailed questions about my work, and how I may have gone about certain tasks differently.
- How might you have optimized parameters for this model differently?
- You just have to create a predictive model from a couple csv files they send you.
- How would you tune a random forest?
- He was kind enough to answer a lot of questions, and asked an open-ended yet very specific question about the shopping process they're trying to optimize. Despite the ambiguity of the problem it felt like he was looking for some particular answers he may have been familiar with. In the end he proposed to send over detailed descriptions of the problem and some actual data, and asked for the solution to be coded up and sent back.
- The problem he asked to be solved is one of their most immediate business challenges, full-blown, not a coding test or even a restricted example at all. So it was odd they'd expect you to work on something for a week that an actual employee would spend several weeks refining. I thought it was to demonstrate coding and analytics skills, and provided a succint, well-commented solution, but didn't try to overdo it. 
- Then I had an analytical case where I had to build and explain a mode. Next I had an in-person interview which was another analytical challenge, but more whiteboarding. It included a data scientist and the hiring manager, who seemed great to work with. Lastly I chatted with the CEO who was friendly and down-to-earth.
- Explored various ways of monitoring user growth and retention.
- 


## Insight Alum Mock Questions

- Instacart (a grocery delivery app) implemented a pickup option at a subset of grocery stores that partner with the company. The subset of grocery stores that got the pickup option was not randomly assigned. How would you figure out whether the revenue from pickup is incremental to delivery? In other words, is pickup cannibalizing delivery?

- At Instacart, if you order 1-7 items, the delivery window is 1 hour. If you order 8-24 items, the window is 2 hours. If you order 25+ items, the window is 4 hours. Why is this approach problematic?

- Imagine Instacart is rolling out a program which allows grocery stores to reduce wait times for pickups. Design an experiment for this program. 



## Insight from Jeremy on Kaggle

from [here](https://www.kaggle.com/c/instacart-market-basket-analysis/discussion/34200#latest-262904)

How is time spent?

- 5% getting the data (if working with a new data source, this is higher)
- 10% analyzing the data (understand context, build intuition)
- 10% manipulating the data (combining many sources, manipulating in non-trivial ways)
- 25% modeling R&D (trying out different algorithms, backtesting)
- 25% putting into production (scalability, testing, app integration)
- 5% documenting (making it easy for future self and / or others to follow)
- 5% A/B test setup (setting up key metrics for success, resolving design decisions)
- 10% deployment (flipping a switch and then dealing with any issues)
- 5% maintenance (if not immediately iterating, ongoing maintenance for other changes)

How are projects evaluated?

- Metric impact. If we moved target metric by Y, how much would it matter to the business?
- User influence. If we changed the product, would it affect the users and drive the metric?
- Product leverage. If we built X, could we change the product to affect users?
- Data availability. Do we have the data needed? (If not, let’s collect it!)
- Algorithm feasibility. Is it feasible to solve, do we have a best practice, can it scale?











