---
title: "LinkedIn Notes"
author: "Mac Strelioff"
date: "`r Sys.time()`"
menu:
  InsightStudying:
    parent: Foundations
    weight: 99
output:
  blogdown::html_page:
    toc: true
    toc_depth: 4
math: yes
linktitle: LinkedIn Deep Dive
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(entropy)

# set seed for reproducability
set.seed(10201991)
```

# Company Visit

## Chris info -- 

- DS people generally get interviewed on computer engineering topics -- eg implementing data structures from scratch, ... 
- Interview centrally for AI organization, then get matched with a team. 
- Module on CS which is like data structures, 
- LeetCode medium, but also more of a conversation
- Binary converter from scratch
- Being able to describe process
- ML on fundamentals of ML, basics and some applications
- Optional product design module
- lots of coding things on a whiteboard
- coding style matters / code should be interpratable
- making sure code would work, eg walk through an example or test cases, think of edge cases

# Recruiter Call

Graydon, sr recruiter at linkedin

- talks about roles, ... . 
- product team

- Role? 
- mission: create economic opportunity for members of workforce. Help people, as many as possiblt. 
- inclusivity -- economic opportunity, and recommending users to recruiters. 
- How do we deploy products that highlight and empower users to 
- Smart Products: recommend learning products based on career progression
- Business side: LinkedIn really white collar dominant, need to include blue-collar workers on LinkedIn.. 
- Or.. partner with governemnts to address skills gaps.. 
- for background and how it relates;;
- "Take intelligent risk": intelligent means is there data to support actions..? My job. 
- DS works closely with a product or user group, doing end to end functionality.. An opportunity to identify ways where things can be done better. --
- END TO END proactive DS work: 
- interview towards a general profile -- manipulation, problem solving, stats, ... . 
- Allocate after passing onsite. 
- Some teams more ML, causal inference, experimentation. 
- 40 positions open now.

- Expedite process? Onsite Friday.. 

- directly to onsite. 
- will send a application for a data scientist. Will probably get application by end of week / later tonight. Make sure core skillset looks good. 
- apply, He'll be notified, and send an introduction email to Shana for scheduling, onsite, offer. 
- Then Shana will assist through onsite process. 

- can maybe have the onsite on Monday. will be flagged as urgent.

- Next steps / interview timeline? 
- Ping if I hear nothing by Friday. 

- Why linkedin -- role sounded awesome when presented at Insight. After looking into LinkedIn more, I came across papers on inferring latent user types, and that kind of work is really interesting to me. Generally though, I'm interested in experimentation roles and sequential testing, efficient experimentation and optional stopping. 

# Recruiter emails II \& III -- Interviews

Here is the outline of what to expect from your onsite in terms of the structure:

## Schedule and interviewers:

- 10:00 AM – 10:45 AM | Host Manager | [Joonhyung Lim](https://www.linkedin.com/in/joonlim/)
- Growth, user acquisition, and user onboarding
- 10:45 AM – 11:30 AM | Statistical Modeling | Dongping Jing maybe [Dongping (sunny) Jing](https://www.linkedin.com/in/sunny-jing-ab530848/) and [Caitlin Crump](https://www.linkedin.com/in/caitlincrump/)
- 11:30 AM – 12:30 PM | Lunch | [Nuo Wang](https://www.linkedin.com/in/nuo-w-486b3027/)
- 12:30 PM – 1:15 PM | Data Manipulation | [Xianyun Mao](https://www.linkedin.com/in/xianyun-mao-232ba916/)
- 1:15 PM – 2:00 PM | Stats A/B Testing | [Qiannan Yin](https://www.linkedin.com/in/qiannan-y-10987ba4/) and [Yuan Chai](https://www.linkedin.com/in/yuan-chai-11127047/)
- 2:00 PM – 2:45 PM | Product Case Study | [Gigi Zhang](https://www.linkedin.com/in/gigizhezhang/)

## 10:00-10:45 | Host Leader | [Joonhyung Lim](https://www.linkedin.com/in/joonlim/)

One of the interviews will be done by a host manager; this person may, or may not, end up being the final hiring manager, but will be able to provide you with information on the different projects, engineering team culture, challenges, etc. He/she will be asking you about: 

- your career history
- your job search (why you’re looking, why is LinkedIn interesting, what technologies are you interested in)
- and an overview of interesting projects you worked on, and your involvement in these projects.

- [Joonhyung Lim](https://www.linkedin.com/in/joonlim/)
- Growth, user acquisition, and user onboarding

- Overall: Excited about their products, their work (experimentation research, psychology in terms of identifying who wants to change jobs and what opportunities would be attractive), and culture (InDay, creating economic opportunity for all).
- My family is mainly construction workers and mechanics, which is a demographic that LinkedIn could expand to.. 
- Construction -- work with unions to find employment for qualified workers, and with contractors to find jobs.
- More generally, LinkedIn could create a marketplace for union workers and contractors. 
- Amazon has mturk for very low-skill tasks, LinkedIn could create a marketplace for higher skill gigs, freelance work, temp work, and contract work.

- Areas for growth: 
- Services: resume drafting, job description drafting, HR system software for industry (could link it with corporate Office products) and get more data about the probability of an applicant attaining an offer. 

- History: PredictIt project, strategy inference, decision making
- Job Search: Generally like experimentation roles. I was first interested in LinkedIn because the anti-abuse team sounded awesome. I also liked the demo experience, there was a big turn out, and people seemed engaged. But overall the most exciting thing to me has been how company culture manifests in things like InDay, where individual across the company take time to give back to the community. I also really like the value that LinkedIn adds, and the direction LinkedIn seems to be going in, in terms of identifying the skills a person can learn to advance their career and advertising helpful resources to them. Thinking about my own journey through academia and now into data science, I spent a lot of time browsing Coursera, YouTube, and various online resources -- I can imagine LinkedIn learning becoming a streamlined product for independent lerarning that basically syncs with your professional LinkedIn profile. 
- I like the idea to [engage high school students](https://engineering.linkedin.com/blog/2015/11/video--higher-ed-team-seeks-to-predict-collegiate-futures), and opening access to knowledge of hiring practices, career trajectories, and salary ranges. I come from a family of construction workers, so I was very much a black swan while figuring out how to navigate through community college, undergraduate school, and graduate school, and now into a technical career. I grew up in 'blue collar' world, and broke into the academic world, and now I'm jumping into 'white collar' technical industry world. This was really hard, and required a lot of self-learning and building professional relationships -- so I very much understand the value that LinkedIn can add for people like me. 
- So yeah I can see LinkedIn as something that moderates the education market, and the labor market -- and based on my experiences navigating these things mostly on my own, I'd be really interested in contributing to products that democratize education and professional connections. 
- Also really interested in the almost academic work that has come out of LinkedIn -- I found papers on inferring user attributes, which is a very similar problem to one of my favorite projects in grad school. For that project I (kid gambling, strategy inference project). 
- Also interested in the economics work (see others in 'excitement' section below)
- Overall, exciting work and a culture / mission / potential that resonates with me. 
- Online Bayesian Logistic Regression: 

## 10:45-11:30 | Statistical Modeling | [Dongping (sunny) Jing](https://www.linkedin.com/in/sunny-jing-ab530848/) and [Caitlin Crump](https://www.linkedin.com/in/caitlincrump/):

- Evaluate and asses analytical thinking and familiarity with the LinkedIn Platform.
- Assess your ability to take business context and translate to an analytical problem
- Evaluate experience working with statistical modeling techniques
- Testing/Training/Evaluating models
- Asses knowledge of model methodologies

- [Caitlin Crump](https://www.linkedin.com/in/caitlincrump/)
- 9yrs
- Working on Publishing - our news writing and news reading experience. Trying to answer questions like;
- Can we tell that something is relevant or good before anyone has even seen it? 
- Are our top writers/ influencers happy when we make changes on the site?

- [Dongping (sunny) Jing](https://www.linkedin.com/in/sunny-jing-ab530848/)
- Market research and product analytics
- Connection Requests Deepdive for Network PVOM; MoT Drivers Analysis; ABI Funnel Deepdive; Unwanted Invites Analysis
- proof of concept (POC), another term, not mentioned; proof of value (PoV)
- Market Research Analytics: Developing product journey data for all product areas (wvmp, abi, jymbii, etc...) and finding important drivers of NPS and MoT Surveys through Machine Learning and Statistical analysis; 

Mention: 

- Wanting to write a blog, considered Wordpress, Medium, LinkedIn -- Liked that LinkedIn was a platform where what I write would get high quality exposure, but didn't like the interface -- particulatly that I couldn't figure out how to write a post in syntax like R markdown. 
- Ended up making my own website with blogdown. 
- Ask Dongping about her work -- can draw on this later in product analytics interview.

Tips:

- Review variables / metrics in analytics section.

 TODO: 
 
 - LOOK UP OVERFITTING, and how to detect it
 - Look up confusion martix
 - Look into POC, POV

## 11:30-12:30 | Lunch | [Nuo Wang](https://www.linkedin.com/in/nuo-w-486b3027/)

- [Nuo Wang](https://www.linkedin.com/in/nuo-w-486b3027/)
- 4yrs, 3 years in consumer behavior at other companies
- LinkedIn Pages, Ads - I am hiring experienced DS who is passionate about shaping product roadmap and strategy through data!

Mention:

- 

## 12:30-1:15 | Data Manipulation | [Xianyun Mao](https://www.linkedin.com/in/xianyun-mao-232ba916/):

- Goal: assess ability to manipulate and analyze data for extracting insights
- Usually at least 1 SQL question + 1 R or Python question
- Familiarity with SQL AND R or Python is required for Senior Data Scientist.
- Determine familiarity of advanced analytical functions

- [Xianyun Mao](https://www.linkedin.com/in/xianyun-mao-232ba916/)
- 1yr, 2.5 yrs previous companies 
- Behavior modeling and predictive analytics

## 1:15-2:00 | Statistics & A/B Testing | | [Qiannan Yin](https://www.linkedin.com/in/qiannan-y-10987ba4/) and [Yuan Chai](https://www.linkedin.com/in/yuan-chai-11127047/):

- Design and analyze experimentations, understands basic stats concepts (e.g. hypothesis testing, mean, variance, probability distributions, sample size calculation, power calculation...) and how to apply them in a business setting.
- For Sr DS, must show an in-depth understanding of A/B testing is needed (e.g. multi-variant testing, sample size calculation, power…)
- Asses knowledge of probability

- [Qiannan Yin](https://www.linkedin.com/in/qiannan-y-10987ba4/) 
- 2yrs
- Statistics PhD, worked on fMRI and agent based modeling

- [Yuan Chai](https://www.linkedin.com/in/yuan-chai-11127047/)
- 2yrs, 2 yrs previous analytics
- Data analyst with extensive experiences on increasing user engagement, improving product & campaign performance, and optimizing ROI with experimental (A/B test, MVT) & exploratory research (classification/clustering/regression).

## 2:00-2:45 | Analytics Case Study | [Gigi Zhang](https://www.linkedin.com/in/gigizhezhang/):

- To assess ability to solve a business case with the right analytical approach and reasonable data intuition; and the ability to make relevant product recommendation based on data insights.
_ Asses your familiarity with the LinkedIn Platform
- Ability to correctly communicate and present solutions

- [Gigi Zhang](https://www.linkedin.com/in/gigizhezhang/)
- 7months, around 3 years prior consulting experience
- Insight Fellow 2017
- Strong in ML

Variables: 

- 

LinkedIn Metrics: 

- VPI (views per impression) for a job recommendation
- API (applications per impression) for a job application
- Job fits: Person-Environment (P-E) -- comprised of Person-Organization (P-O), Person-Vocation (P-V), Person-Group (P-G), and Person-Job (P-J) fits

### Users

- Businesses, recruiters
- Content creators
- Job seekers
- Students picking a college
- College admin seeking alumni networks
- Networkers, wanting to keep in touch with classmates and coleagues

### Current issues

GROWTH: LinkedIn is now backed by microsoft, wants to develop new products, and acquire more users -- particularly those in underserved segments like blue collar labor. 

### Ideas and excitement

Ideas: 

- For blue collar workers, again become a marketplace, somewhere where contractors (blue collar) can meet with union workers and bid on contracts, similar to Yelp's segment for contractors. 
- The AirBnb or Uber of consulting / freelance work. I've been interested in consulting work. LinkedIn seems to be in an excellent position to become a platform or marketplace for consultants or freelance work.
- market to lower level education, which LinkedIn is already working on with their student future products (students can see what colleges are associated with careers and companies they like).
- Insight, lots of other interview prep that LinkedIn might be able to assist with.. Eg resume review verticals, behavioral interview questions, mock interviewing services, Coding practice like LeetCode (see that this is being worked in with skill quizes).

Excitement:

- I like their general work on [inferring user attributes](https://engineering.linkedin.com/teams/data/projects/jobs), 
- [economic research](https://economicgraph.linkedin.com/research#all), 
- [experimentation research](http://web.media.mit.edu/~msaveski/assets/publications/2017_detecting_network_effects/paper.pdf) (also [here](https://dl.acm.org/citation.cfm?id=2488509&dl=ACM&coll=DL), [here](https://engineering.linkedin.com/blog/2019/06/detecting-interference--an-a-b-test-of-a-b-tests)), 
- [latent user research](https://dl.acm.org/citation.cfm?id=2741126), 

### Excitement from Recruiter

- [Student Future](https://engineering.linkedin.com/blog/2015/11/video--higher-ed-team-seeks-to-predict-collegiate-futures), a product to help high school students choose universities, based on entering a company and a role and seeing statistics about the schools that people with those jobs attended. 
- [InDay](https://blog.linkedin.com/2015/07/29/inday-investing-in-our-employees-so-they-can-invest-in-themselves) -- LinkedIn officially takes one day a month to allow employees to give back to the community, company, or themselves in some (themed) way.
- [Economics graph](https://economicgraph.linkedin.com/resources/linkedin-workforce-report-may-2018) project that gives reports on skills gaps and migrations. 
- I noticed the job ad emails that I get seem based on my job search, possibly more-so than my skills.. Do you think you'd get more retention / engagement by recommending jobs based on skills or degrees and work history, rather than past searches? Or at least exploring this -- randomizing emails to suggest jobs based on search vs based on skills and experience. 

## Onsite


### Glassdoor interview questions

Given a random generator that produces a number 1 to 5 uniformly, write a function that produces a number from 1 to 7 uniformly or something like that.

Solution 1: $x^{log(7)/log(5)}$

Solution 2:
```{python,eval=FALSE}
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from random import randint

def rand5():
    return randint(1,5)

# generate random integers from 1 to num
def rand7(num):
    r=0
    for i in range(num):
        r += rand5()
    return r % num +1

b= np.zeros(100000)
for count in range(100000):
    b[count] = rand7(7)
_= plt.hist(b) 
Counter(b)
```


- How many active members in LinkedIn right now? What is the business model at LinkedIn? Basic SQL as long as you finished most of questions in Hackerrank.  
- design recommendation engine for jobs
- How can you help to improve sales given a LinkedIn database  
- Talk about a product that you wanna build at linkedin  
- Product analytics case study around Linkedin profile  
- There is a table of page view data. Two columns: Member ID and time stamp. You can assume this is for a 24 hour period. Members vs. guests/visitors are differentiable via ID's. Have to come up with a method for determining which all activities are crawler related (and not my members) and write a query for the same as well.  
- Using a set of tables, how would we find out whether users have a certain feature on or off?  
- What is the optimization problem for a SVM?  
- How many lines do you think a users' daily login table has? And a general SQL question about joining two table with some conditions.  
- What product metrics do you construct? How to tell if your experiment is successful?  
- I was asked to come up with some of the factors that could be used to produce certain algorithms ('people you may know,' and an algorithm to discover when a person is starting to search for new job).  
- The Interviewer ask the running up staircase with n steps quesion which need to get how many possible ways to run up the stairs. Each time you can hop either 1 step, 2 steps or 3 steps at a time. In addition, he asks some question about my research such as graph algorithms.
- I had 3 phone interviews with Linkedin data scientists. Everyone I spoke to was very bright, thoughtful and polite and made a great impression. On the first two calls I was asked how I would solve some of the problems Linkedin worked on (ex: people you may know) and on the third call I had a more technical coding interview. However I didn't have a machine learning background at the time, so they did not give me an offer but encouraged me to e-apply after I had taken some of the machine learning classes I was planning to take the next semester. Considering how little machine learning I knew at the time it's a wonder they even gave me a first interview, let alone 3.
- There is a significant increase in linkedin signups in this month. How much of this will you attribute to the changes you made in signup process. What data-points would you look into to confirm/deny this?  
- Implement pow function. 
- Segment a long string into a set of valid words using a dictionary. Return false if the string cannot be segmented. What is the complexity of your solution? 
- find out k most frequent numbers from incoming stream of numbers one the fly.
- generating a sorted vector from two sorted vectors.  


- Seemed every interviewer asked a variant of an A/B test for the homepage.  
- design A/B test  
- SQL, Coding (R/Python), Product Case, Machine Learning, Stats  
- A few simple SQL queries with joins.  
- Two questions were asked, both about searching in sorted arrays of numbers. The second interview was almost identical, except that the question was more about algorithm design, which required general problem solving skill.
- I don't recall exactly, but they asked about how I would approach several scenarios. This would be very difficult to answer well if you have not worked at a similar company and know what sorts of data are available to answer the question.  
- basic data mining questions, including the concepts of classification and clustering; and a simple dp question which is quite similar to "Climbing Stairs", and failed the second one right after I came back from another state (basic nlp questions, like named entity extraction, and basic data mining questions, like SVM, naive bayes; and a sampling question which is quite similar to Reservoir sampling).  
- The first interview was to test my SQL/R coding skills. The second interview was around experimenation - A/B testing, metrics etc., The third interview was on a bit of probability, machine learning techniques . The final one was with director of data science on a case study related to some linkedin scenarios and overall career interests. Even though all the interviews were set-up without any delay, what surprised me is that I didn't receive any response from the HR after all the interviews. I followed up for a month or so multiple times, but I received absolutely no response, which I have no clue why.
- Questions around current / previous experience and education. 
- Important metrics to think of in relation to LinkedIn data, to be included in dashboards available to executive level. 
- Questions around SQL, R, and Python.  

# Knowledge gaps

- Lots of questions about the platform
- Causal inference: how to construct a synthetic control, e.g. for estimating from historical data the impact of a email nudge on different user behaviors
- Advantages / disadvantages of different ML models (why logistic regression? How would you interpret the coefficients in a logistic regression model?) 
- Causal inference: How to identify who would be successfully nudged by an email, ie a decision system for sending an email nudge that doesn't feel like spam.
- SQL, Python: counting ids with more than 1 null

# Next steps

- LinkedIn message Caitlyn -- her work sounded exciting. Mention finding some research papers from LinkedIn on user modeling, and ask for possibly more papers to look into!
- Send thank you email to recruiters























