---
title: "Pinterest"
author: "Mac Strelioff"
date: "`r Sys.time()`"
menu:
  InsightStudying:
    parent: Foundations
    weight: 99
math: yes
linktitle: Pinterest
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(entropy)

# set seed for reproducability
set.seed(10201991)
```


# TODO: 

- Be able to list growth strategies
- Be able to outline and work through experimentation problems
- be able to list key metrics for growth, retention, engagement (mentioned throughout quarterly filing)

- job description [here](https://careers.pinterest.com/careers/details/1807876)
- Articles from [Pintrest labs](https://labs.pinterest.com/projects/data-science/)
- [Letter to shareholders](https://s23.q4cdn.com/958601754/files/doc_financials/2019/q2/shareholder-letter-Q219-v10.pdf)

# Ideas: 

- AR to show a product in the person's house (built on the [lens/picture-based search feature](https://newsroom.pinterest.com/en/post/upgrading-lens-for-more-online-to-offline-inspiration))
- Registery or 'wishlist' pinboards for weddings, baby showers, holidays, birthdays, ... 

# Onsite Prep

Growth initiatives: 

- Grow userbase to males? 
- Grow other demographics?
- Look deep into product experimentation beyond just A/B designs
- [selecting A/B testing metrics](https://towardsdatascience.com/a-guide-for-selecting-an-appropriate-metric-for-your-a-b-test-9068cccb7fb): Point is that late funnel metrics might require a larger sample size because of the smaller effect size

From [Risks](https://s23.q4cdn.com/958601754/files/doc_financials/2019/q2/93a68ae2-b0f2-47d5-a14e-757e66a6f421.pdf):

- Important metrics: growth, retention, frequency and duration of engagement or use. 
- Ad spend to acquire new users and retain current users
- Audience approximately 43% of US internet users, 80% of women age 18-64 with children [user demographic](https://www.comscore.com/Insights/Blog/What-Potential-Does-Pinterest-Have-as-an-Advertising-Platform)
- Maybe saturated with that demographic and need to grow to other demographics like men and international users
- Pinterest requires good data, targeting areas with high smartphone penetration. Has partnerships with some data providers so that Pinterest doesn't count toward user's data quotas. 
- Not anticipating that majority of users will become DAUs
- Risks:
- competitors mimic product, users use competitiors more
- User expreience degrades because of poor company decisions
- failure to deliver relevant content
- third parties pull content
- software issues
- bandwidth issues, slow and frustrating experience
- privacy and security concerns
- spam, harassment, cyberbullying, ... 
- taking actions to maintain engaging and relevant content which lead to lower ad revenue
- continuously monitor ads, too many ads or irrelevant ads could hurt user growth, retention, or engagement
- future data privacy laws
- 


[Funnel Examples](https://www.crazyegg.com/blog/ecommerce-conversion-funnel/)

- Awareness: Keep the product at top of mind
- Interest: 
- Desire: emphasize benefits to the user and a call to action. E.g. "sign up for (product) and enjoy (benefits)"
- Action: 
- Example: sessions > sessions with product page view > sessions with Add-To-Cart > sessions with transaction
- User flow to see if users behave differently from the first touch
- Important metrics: traffic > conversion rate, bounce rate > sales, cart abandonment > 

7 Growth Strategies from [here](https://sujanpatel.com/marketing/growth-levers/)

1. Pinterest: Exclusivity. Pinterest began as an invite-only platform. 
2. PayPal: Buy users. PayPal offered monetary rewards to new users. An alternative is cash back, since that first requires a purchase. This can be less than a customer's LTV tokeep resaonable revenue.
3. Popcorn Metrics: Deep Onboarding. Working personally with new users, providing videos and tutorials. 
4. SpringShield: viral referral loop. Like Robinhood, can have a waitlist for a new feature and make your position in line contingent on referrals -- this induces a competition that favors users who successfully refer more users. 
5. GrooveHQ: Segment marketing emails based on user behavior. Targeted differet users with statistics (time on page, and logins per day) resonent of the users who churned within a 30 day window. Also measured response rate and retention rate among those who responded to the email. 
6. Milkshake: Leverage happy customers for referrals. Using NPS (Net Promoter Score) responses (positive ones, of course) as testimonials. Asking for shares inside Mailshake. Engaging referrers by asking at sign-up if a customer was there via a referral and who gave it, and thanking them via social media and email. Increasing customer/product investment by asking our most active customers for product feedback. Conducting and featuring case studies from our most successful customers.
7. PicMonkey: Freemium. 

[Letter to shareholders](https://s23.q4cdn.com/958601754/files/doc_financials/2019/q2/shareholder-letter-Q219-v10.pdf): 

- Introduced personalized search in home and sidebar.
- More video content: user repin rate for videos is 1.4x that of static images. Video views greater in Q2 than all of 2018. Searches for specific terms (paint on canvas) also increased by >300% after video pins on those topics. Big gains in searches in food, style, beauty, and skill learning.
- Videos also improve clickthrough rate and can have a lower cost per click for advertisers (ads pay for impressions and ranking, so a higher CTR may imply a lower CPC).
- Focusing on growing products from retailers, saw increase of 50% from methods for acquiring pin inventory, which improves relevance and engagement, measured in weekly shopper impressions and clicks. 
- New [shopping features](https://newsroom.pinterest.com/en/post/summer-shopping). Retailers saw [2x higher return](https://business.pinterest.com/en/blog/research-retail-brands-can-see-2x-higher-returns-on-pinterest-than-other-digital-channels) on ad spend with Pinterest vs social media, and 1.3x higher return than on paid search. 
- New mobile ad manager that increases mobile signup activation rates
- Made easier to add tags for ad attribution, 2x more tags added YTD in 2019 than in all of 2018
- 30% YoY DAU growth to 300m




### Metrics

MAUs and ARPU depend on the methodology used to track user data, and changes in this methodology can influence Pinterest's revenue projections.

Retention:

- MAU: Monthly active users, a logged-in Pinterest user who visits our website or opens our mobile application at least once during the 30-day period ending on the date of measurement. 

Revenue:

- ARPU: Average revenue per user = revenue in a grography / ((MAU0 + MAU1) / 2)
- Where MAU0 is for the same 30 day period as the revenue and MAU1 is for the prior period



# Phone Screen

```{eval=false}
This is just a simple shared plaintext pad, with no execution capabilities.

When you know what language you'd like to use for your interview,
simply choose it from the dropdown in the top bar.

You can also change the default language your pads are created with
in your account settings: https://coderpad.io/settings

Enjoy your interview!



Your previous Python 3 content is preserved below:

# def say_hello():
#     print('Hello, World')

# for i in range(5):
#     say_hello()


# 
# Your previous MySQL content is preserved below:
# 
# /*
# Write a query to calculate the Average revenue generated per user for US users in first 10 slots for each advertiser on a given date
# 
# pick any date
# 
# 
# 
# ad_events                             user_dimension
# +---------------+---------+           +---------------+----+
# | user_id       | int     |           | user_id  | int     |
# | advertiser_id | int     |           | country  | varchar |
# | slot_id       | int     |           | age      | int     | 
# | revenue       | int     |           | gender   | varchar | 
# | dt            | date    |           | spam     | int     | 
# +---------------+---------+           +---------------+----+
# 
# 
# ad_events                             user_dimension
# ad_id | uaser_id                         
# 1
# 1
# .
# .
# .
# 
# 
# 
# Want: 
# +-----+
# ad_id   | avg rev per user for firt 10 slots
# ad1        .89      
# ad2        .90
# +---+
# 
# */                      
# 
# 
# select SUM(a.revenue)/COUNT(distinct a.user_id) as avg_rev_user_advertiser, a.advertiser_id
# from user_dimension u
# join ad_events a
# on a.user_id = u.user_id
# where a.slot_id <=10 and u.country = "US"
# group by user_id
# 
# 
# 
# /*
# Write a query to calculate the number of repeated ads for each user on a given day
# 
# user_insertion                        ad_insertion
# +---------------+---------+           +---------------+--------------+
# | user_id       | int     |           | insertion_id     | int       |
# | insertion_id  | int     |           | promoted_pin_id  | int       |
# | dt            | date    |           | action_type      | varchar   | 
# +---------------+---------+           | action_timestamp | timestamp |    
#                                       | dt               | date      | 
#                                       +---------------+--------------+  
# 
# user_insertion sample rows:
# 
# user_id  insertion_id         dt
# 1        hofh38u9uvhcc   2018-09-29
# 2        abcddh99840cc   2018-09-29
# 3        ueiruoeir0419   2018-09-29
# 
# 
# ad_insertion sample rows:
# 
# insertion_id    promoted_pin_id   action_type   action_timestamp   dt   
# hofh38u9uvhcc   1234              impression    1530793815         2018-10-01
# abcddh99840cc   1234              click         1530793815         2018-10-01
# ueiruoeir0419   1234              save          1530793815         2018-10-01
# 
# 
# uid pid count
# 1   1    1
# 1   1    4
# 
# 
# want: 
# Userid, Number_of_repeated_ads (number of ad pins that were repeated)
# 1        5
# 2        9
# 3        0
# 
# 
# */
# 
# select sub.user_id, count(*)
# from
# (
# select u.user_id as user_id, a.promoted_pin_id as pin_id, count(*) as repetitions
# from user_insertion u 
# join ad_insertion a
# on u.insertion_id = a.insertion_id
# group by u.user_id,a.promoted_pin_id
# having count(*) >= 2
# ) as sub
# group by sub.user_id
# 
# # within users, count unique, repeated pin ids
# 
# 
# 

import numpy as np
import pandas as pd
import random


user_ids = list(np.random.choice(range(1000000,1001000), 1000))
impressions = list((np.random.pareto(a = 3, size = 1000)*1000))
impressions = [int(i) for i in impressions]
clicks = list((np.random.pareto(a = 3, size = 1000)*100))
clicks = [int(i) for i in clicks]
data = pd.DataFrame(np.column_stack([user_ids, impressions, clicks]), columns = ['user_id','impressions','clicks'])
data.head()


# code generates dataset
# 

# Does this dataset make sense? - What will you check ?
# 1) user 2 more clicks than impressions

# How will you clean it up ?

tmp=data['impressions']<data['clicks']
tmp.all()

# data = data[data['impressions']>=data['clicks']]


###


We currently have a button on each Pin on the Pinterest app. It has a click rate of 0.04 (number of clicks / number of pins seen). The only outcomes possible are click or not click.

Q: What is the probability of observing exactly 5 clicks out of 100 pins seen?

100 choose 5 * .04^5 * (1-.04)^(100-5)


Q: What is the probability of observing at least 5 clicks out of 100 pins seen?

1 - sum from i = 0 to 5 (100 choose i * .04^i * (1-.04)^(100-i))


Q: Given that we observe 5 clicks out of 100 pins seen in the treatment group of an experiment, construct a hypothesis test to test whether the button click rate is significantly different than 0.04.


p_0 = 0.04
p = 5/100
n = ? 

z = (p - p_0) / (p_0 * (1-p_0) / sqrt(n) ) 
z = (.05 - .040) / (.04 * (1-.04) / sqrt(n) ) 


Q. Can you describe what alpha of 0.05 means here (i.e., type 1 error rate)? To a data scientist (technical audience)? To a person with no statistical background (non-technical audience)?


Q. Can you describe the outcome of this hypothesis test to a data scientist (i.e., to a technical audience)? To a person with no statistical background (i.e., to a non-technical audience)?

p>.05

Experimentation

We have been getting feedback from users in focus groups that they’d like to see fresher search results, meaning more up-to-date pins. So we’d like to see how freshness would affect user experience. 

Q: How would you approach this problem?

freshness [?] -> user satisfaction?

1) define freshness

2) metrics to reflect a better user experience

Acquisition
- 

Activation
- time on home page
- boards created
- pins per board
- pins pinned per user

Retention
- repeat logins / week

Referral
- 

Revenue

```


Pinterest
- Python, data munging, pandas
- SQL care about efficency (e.g. reduce data before joining)
- probability questions; 
- - Clickthrough rate of x, what's p(5 out of n click through)
- - fundamental probability
- business case; open case study..
- behavioral

## Behavioral 

### Background 

Example Answer: 

- I recently graduated from UC Irvine where I studied cognitive science and statistics. 
- My research focused on decision making, which means I programed experiments that would show people two or three alternatives and vary the attributes of the alternatives to reveal how people are making decisions. 
- So for example someone might see three different pins -- These pins have attributes like different properties of the image, maybe different text captions. 
- Search for recepies, then I might immediately see 3 pins with food images that have different attributes (carbs, brightness of the image, text, ...). 
- Very relevant, which is one of the reasons I'm excited to be interviewing with Pinterest. 

- That overlap between the tasks I created, and the user experience on the pinterest platform is one of the big reasons why I'd be excited to work at Pinterest.
- Another reason is the proximity of user data to user purchasing decisions (high user intent). 



- UCI
- Cognitive science and statistics
- My research focused on decision making -- 
- 1) How environmental cues impact impulsivity or preferences for immediate rewards
- 2) Decoy effects -- so how the attributes of an undesirable option can influence preference between two desirable options. 
- 3) Inferring which decision making strategy a person is currently following
- For all of these studies, I was writing programs that would show participants multiple options (e.g. pins) and modify the context (adding other cues) or the attributes of the options to see how those modifications influenced the probability of a person picking one of the options. 
- Very relevant to the kind of environments users experience on Pinterest, which is one of the reasons I'm excited to be interviewing with Pinterest. 


- One of the phenomena that I studied was the decoy effect -- For example at Pinterest, if a user sees a set of three pins (A,B,C), they pick A 70% of the time and B 30% of the time, but when we just show pins A and B, they pick B 55% of the time and A 45% of the time. 


### HaaS freelance work

Situation: 

- Haas stands for housing as a service, it's a membership-based coliving startup.

Task: 

- Want to increase memberships through facebook and google ads. 
- I'm leveraging a little SEO experience to help with designing ads; 
-     Brighter photos, photos with faces, and color schemes that contrast FB's color scheme of white and blue, 
-     thse features are associated with higher CTR for YouTube thumbnails. 
- Becoming familiar with Google Analytics and Facebook Ad Analytics to run A/B tests with these ads

Action: 

- See which drive more interest in CTR, and more conversions in applications for membership, and which attract the demographics that my client wants to attract.

### Insight Project

Situation: 

- 2 week consulting project
- Startup focused on digital workspaces (e.g. google docs)
- Wanted to understand user base.
- Wanted to be able to predict who would convert from a free trial to a paying customer.
- (skip) Wanted to attribute conversion to product features with conversion.

Task:

- Data: 
- Company demographic information, company size and revenue. 
-     Used this to communicate conversion rates by demographic to heads of different teams using tables and figures.
- Account activity data which was a sum of actions taken within an account each day. 
-     I transformed this into cumulative sum instead of daily sum to increase interpretability and modeling ease. 

(skip) Action: 
(skip) - Used cross sections of cumulative account activity data after 7 days since the account was created. 
(skip) - Cast as classification problem, used SMOTE to address class imbalance,
(skip) - used 5-fold CV to evaluate models on AUC, 
(skip) - ended with a RF algorithm for these predictions. 

Result: 

- Delivered presentation and slide deck with tables and figures to a group of team leaders. 
- Delivered a Python script to implement the model, and a slide deck describing the modeling procedure and performance. 

### PredictIt project

Situation:

- Prediction markets aggregate information and incentivize rational behavior, so one would expect the prices to be accurate. 
- At an individual level, lots of fallacies have been established in lab settings.
- I wanted to know if any fallacies would manifest in market prices. 

Results:

- Conjunction fallacy: "Trump" traded higher hand "Republican" for extended period of time.
- Disjunction fallacy: Most market prices add up to something greater than $1, but because of fees it's often not profitable to take advantage of this. 
- CPT subjective probability function: Overpricing of low probability events and Underpricing of high probability events
- -- notably this was highest as expiration approached, a context that is more similar to lab studies that don't have delayed rewards. 

- Now we're working on automating trades based on these and other indights. 

### Quantopian: 

- recreated XIV, fund that trades VIX futures weighted so that the effective days to expiration is approximately 30.
- mean revision
- moving average crossover

### Child bandit modeling

Situation:

- Wanted to know what strategies they followed, and if their strategy changed over time.
- Kids repeatedly chose between two gambling machines

Action:

- I developed a model that inferred the probability of following each strategy on each trial
- Used Bayes' Rule to smooth out these inferences / accumulate information over trials 

Result:

- Kids do seem to switch strategies, probably don't act optimally, and have different strategies depending on age (switchy vs sticky)
- Result: A lot of experiments focus on which strategy best fits all data across trials -- the approach that I took allows for changes in strategies, and the exciting result was an ability to track latent decision making strategies over time. 

Value:

- Implications for user intent modeling




### Explain some research at Pintrest

See: 

1. [Predicting Intent Using Activity Logs](https://labs.pinterest.com/user/themes/pin_labs/assets/paper/pinning-www17.pdf)

Pinterest: 

- Content sharing platform, and image based search engine
- Prior research found user types; 1) casual browsers, 2) responding to a specific goals
- Prior research found different temporal horizons, e.g. using Pintrest to plan dinner versus using Pintrest to plan vacations.
- On Pintrest users view pins (content) to boards (collections). 
- Pins have 33 categories (DIY, food and drink, ...)
- Users can look at closeups of Pins, which provides additional information
- Users can click through to visit a site affiliated with a pin

Problem and volue of a solution: 

- Users can use a product with different intents, and the material that a user finds valuable may depend on their intent.
- Being able to infer a user's intent from their behavior during a session would enable a personalized experience aligned with a user's goals. 
- Example: Someone looking for dinner recepies might want something they can quickly make with common ingredients, while someone looking for potluck ideas might want more unique dishes, and someone who is just browsing food might prefer a variety of exotic food images. 
- User intent can vary with each session, so quickly identifying intent within a session can help with changing the interface and content shown to the user in real time based on their inferred intent

Current paper: 

- Goals: Understand how intent informs behavior, and whether intent can be inferred from behavior.
- Two dimensions of intent: 
- Goal specificity: whether the intent is stimulus specific (glutin free chocolate chip recepies) or vague (just browsing to pass time).
- and temporal range: Time horizon for goal completion (tonight, next week, next month, ...).
- In psych, motivation is defined as a directing and activating or invigorating force. The directional component maps onto what Pintrest is calling goal specificity, and the invigorating component might map onto the inverse of what Pintrest refers to as temporal range.
- In psych, there's a notion of goal-directed and habitual behavior. The former is driven by a specific desired outcome (similar to goal specificity here) while the later is a less mindful response to stimuli (eg boredom triggers a passive arousal seeking).
- In social psych, attitudes have been thought about along a gradient of specificity -- so maybe things like time-related words in a query can be used to identify goal-directed users.
- Shopping websites can be used for a specific purchase (goal-directed) or in an experiential way (habitual).

Methods: 

- Sample: 5369 females mean age 33.5, 564 males mean age 38.6, all from US and on Pintrest during July 2016
- Survey asking; 
- 7 point likert scale: "Are you visiting Pintrest with a goal in mind?"
- "When are you planning to act on what you're looking for today"
- Question about Pintrest specific motivations (eg finding DIY ideas)
- "What are you looking for on Pintrest today?" Response options were based on Pintrest categories
- Focused on data in the session immediately following the survey
- primarily analyzed first 10 minutes because this window had peak performance, around 27% of sessions had fewer than 10 minutes
- Over 850,000 behavioral events (views, closeups, searches) across 5933 users within 10 minutes.
- Also analyzed behavior from when the user first created account until a week after survey completion
- used Holm-corrected p-values, a method that is more powerful than a the conservative Bonferroni correction.


Mitigating limitations: 

- coverage bias: mitigated by uniformly sampling from users for inclusion
- participation bias: compared activity of users who completed the survey (addigned survey, took survey) to those who saw the survey popup but did not complete the survey (assigned survey, did not take survey). 
- Survey takers had been using Pintrest longer, and had more saved pins. Inferred from this that engaged users were 

Findings: 

- Goal-specific users are: 
more focused, 
search more (1.1 vs 0.4 searches),
spend more time browsing specific categories of content in detail, 
more likely to reference saved content, 
less likely to return in next 7 days,
less likely to attribute their visit to boredom (2% vs 25% for habitual),
more likely to attribute visit to making something (26% vs 5% for habitual)
- users with short term goals:
specific categories of content, 
likely to reference saved content, 
less likely to save new content, 
goal-specific users more likely to act in short term, habitual users more unsure of taking actions
- Demographic differences:
females more likely to be goal-specific (49% vs 40%), 
males unsure of taking action, 
older users more short-term goals, 
younger users more unsure of taking action, 
food, drink, DIY searches more likely to be goal-specific and act in short term, 
travel, entertainment more likely to be habitual and likely to act in long term, 
intent moderates the type of recepies users save
- Model can predict goal specificity and temporal range. 
- Current session data is most informative, historical activity data also helpful

2. [Understanding behaviors that lead to purchasing](https://labs.pinterest.com/user/themes/pin_labs/assets/paper/understanding-purchasing-at-pinterests.pdf)


# Metrics

## Acquisition

- Week / Week new users

## Activation

- Pin likes
- Pin shares
- Pin comments
- Pins created
- Boards creates
- Pins on board

## Retention

- Returning users 

## Referral

- Referral links? 
- New users by source

## Revenue

- Ads clicked
- Ads clicked by user segment
- Ads clicked by location
- Ad conversions (clicks and a microconversion on the next page)













