---
title: "Square"
author: "Mac Strelioff"
date: "`r Sys.time()`"
menu:
  InsightStudying:
    parent: Foundations
    weight: 99
math: yes
linktitle: Square
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(entropy)

# set seed for reproducability
set.seed(10201991)
```


# Square job





# HM Phone Call

Deeksha

- lead for growth DS at Square
- prior to that ... worked at digital ad startup
- Over 10 years of experience
- Square started payment processing, now more of a business solutions company
- more than 30 products
- verticle point of sale product
- support for invoices
- all tools needed to sell something
- Also have giant ecosystem of Cash app, over 20 million consumers, growing rapidly
- going to become a banking app soon. 
- Growing at a rapid speed
- almost doubled over last two years. 
- good company for DS
- Lots focused on personalization -- opportunity to play with different ML techniques, show recommendations to seller. 
- Opportunity to build models/systems that are seller facing
- Over 60 DS who meet regularly. 

Recruiter notes:

- mission is to provide sellers with most remarkable experience in showing the best content and products to them. 
- advertising services to sellers/marketers
- looking for someone who understands impact in terms of dollars

Team goal: Surface right content to right person at right time. 

About Me: 

- Wanted to learn more about the role and talk a little about my experience to make sure I'm a good fit.

My experience: 

- Model-based, Model-free RL models
- Inferring decision making strategies -- Gave people a choice between two gambles (i.e. a bandit task), lots of ways they could make that choice over trials, so we specified different strategies and inferred which strategy a person was most likely following across trials.
- Insight project, random forest model to predict which users would convert from a free trial to paid subscribers.

Possible overlab: 

- Intent modeling
- Retargeting

Production code: 

- Tweet frequencies using poisson process and conjugacy -- negative binomial.  

Questions: 

- What are some open challenges that the team is working on, and what approaches are they thinking of? 


- Tech stack? 


- What methods do you or people on your team frequently use? 
- We mostly rely on tree-based methods over last few years (XGBoost, GBM, RF)
- Implimented deployed model -- GBM
- On stats side, use propensity score matching, CI analysis, lots of AB testing. 
- Those things are done when a model is deployed. 
- On a day to day basis, I'd be on a project in different areas
- Dashboard is a web app that sellers use where they can see their sales, revenue, ... .
- Want to show recommended products, recommender items
- want to build recommender model to see what products are most useful for each seller
- infer what products or business needs sellers would want
- Square capital, restaurant product, invoices product, ... 
- data from onboarding stage
- Signals about payment history, and engagement with apps and products. 
- More than 100-200 pages on website, how do we route sellers to most useful page? 
- Want to do intuitive routing for pages
- Can we predict what are some of the recommended pages that we'd be interested in, cookie data, browsing history?
- 3) score leads. Working with account management and sales, on sales side they want us to recommend or score leads. 
- suppose there's 10k sellers as leads, not all are high value. Want to predict conversion probability score to rank them on probability of converting to a square user.
- Measurement science team -- lots of statistical modeling too. 
- Profile with more statistical techniques, will have a open role on the measurement science team. 
- Lots of experimentation done by product analyst. 
- Measurement science team. 
- Predicts LTV, profit, about seller to help understand the value of the seller. 
- Predictive models, then CI begins when you have a seller using the product, then start using abother product, and want to measure how much incremental LTV the additional product added. This requires statistical techniques. 


- What kind of data do you have on the sellers? 


- What are some things to learn in order to be successful on day 1? 
- Having working knowledge of how to build tree based models
- coding in Python, best practices, start coding on same week
- expected to push PRs -- models in production
- aware of python packages and how to use them
- SKLearn? 
- Tensorflow, SKLearn, .. 

- What can I do to see the product? 
- Can join Square point of sale. 
- Can use square cash but won't be seller side
- Can sign up for Square dashboard
- 



# Recruiter Phone Call

Topics: professional background, interest in square, current role.

[Job ad](https://www.linkedin.com/jobs/view/1502289246/)

- focused on surfacing the right ad to the right people at the right time

About Me: 

- PhD in cognitive science, main research focused on 
- decision making -- where I'd program tasks that showed people different options and ask them to indicate preferences, then change the attributes and see how that influenced preferences. 
- Reinforcement learning -- so I programed simple games, formalized theories of cognition as different reinforcement learning algorithms that played the games, then had people play the games and determined which algorithm they behaved most similarily to. 
- Those projects embody the content areas I'm interested in -- analyzing the choices people make, or their behavior in an app, and how those choices are influenced by contexts and reward systems. 

- Another project that I really drove is a better example of leadership and working in teams. 
- PredictIt project. 
- There are these marketplaces called prediction markets, where people can buy or sell contracts with real money. The contracts pay \$1 if an underlying event occurs, for example one contract might be "Joe Biden will win the 2020 presidential election". The underlying theory is that the price should reflect the probability of the event occurring -- so if that contract was at \$0.7, then Biden should have a 70% chance of winning. 
- One key question is whether the prices are well calibrated -- that is, do 70\% of the markets prices at \$0.7 actually resolve to 'True'? 
- To exaimine this, I reached out to a large online prediction market and gained access to order level data. 

- Growth role: 
- Most similar to analyzing choices that people make and how 
- 8 data scientists
- wide mix of industry experience, phd, eng, open source programming
- Looking to grow by 1-2 more in the next two quarters
- Square has 30 products. 
- mission is to provide sellers with most remarkable experience in showing the best content and products to them. 
- advertising services to sellers/marketers
- looking for someone who understands impact in terms of dollars
- ML systems for personalization
- opportunities to work with text/image data
- Will have opportunities to talk to more DS
- this role is more in the ML and modeling area. 
- working on production code in python
- occasionally contributing to other code bases
- do have more traditional product analytics roles that are more data heavy to push decision making -- though on a lot of DS teams this is often mixed with DS as well as analyists. 
- Growth team primarily DS
- If I want to be data heavy, 
- Exposure to actual modeling and writing production workflows using Python to use ML and stats modeling experience
- DS more meaty in terms of technical work
- PA more data, analytical, pushing insights for actionable decisions

DS role next step: 

- 45 minute technical python interview
- work through everyday problem with another DS to get to a workable solution
- loops, list comprehension
- communication

Sr. Product analyst: 

- More around SQL, data analysis, operational thinking
- 45 min SQL screen hands on working through SQL problem, then a HM screen, then onsite for data analysis

Will send info to the other Sr. analyst role. 











