---
title: "Wealthfront Notes"
author: "Mac Strelioff"
date: "`r Sys.time()`"
menu:
  InsightStudying:
    parent: Foundations
    weight: 99
math: yes
linktitle: WealthFront Deep Dive
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(entropy)

# set seed for reproducability
set.seed(10201991)
```


<!--
LinkedIn summary to consider, form a DS at Wealthfront; 
Skilled in Statistics, Linear Algebra, Data Munging, and Data Visualization. Applications in Regression Analysis, Machine Learning, and Causal Inference. Experience formulating, solving, and communicating the results of impactful business questions. 
-->

# TODO: 

- Looking for: "You enjoy mentoring others on subjects such as causal inference, experimental design, data visualization or behavioral psychology"
- - Make a few videos on experimentation and causal inference

- Work on: "You subscribe to Wealthfront’s values and mission and can articulate the reasons why, and have an understanding of our product, business model and key metrics"

# Job Description

## Projects, Tasks, and Data

- Work closely with a cross-functional growth team of marketers, product managers, and engineers to generate new ideas for growth especially top of funnel, translating open-ended business issues into data questions, identifying practical analytic and A/B testing approaches to validate the ideas, and defining ongoing checks post-implementation to ensure that the growth mechanisms are working as planned. Carry out timely and well-documented analyses that influence our growth and company strategy
- Formally mentor junior colleagues and provide technical guidance to the team
- Continuously look for, and execute upon, opportunities to improve the quality of our data, infrastructure and products
- Understand and communicate a data-driven picture of our clients, product and business (and their interaction) to the company
- Promote the automation of repetitive tasks and the creation of tools over ad hoc analyses, making your insights available to anyone that can benefit from them

## DS Role

- You subscribe to Wealthfront’s values and mission and can articulate the reasons why, and have an understanding of our product, business model and key metrics
- 4+ years of experience operating successfully within a world-class data science team or academic program
- Ability to access, transform, visualize, and model datasets with minimal engineering support, and communicate your results clearly, both verbally and in writing
- A firm foundation, rooted in experience, of the basic tool-box of regression and classification models, as well as causal inference, experimental design and time series modeling
- You can effectively prioritize and objectively edit your own work
- You care about producing reproducible work and have picked up tools to this end
- You enjoy mentoring others on subjects such as causal inference, experimental design, data visualization or behavioral psychology
- You have built something first hand that you’re proud of
- You are currently learning something outside of your immediate line of work
- Programming competency in R, Python, and SQL is a plus
- BS, MS, or PhD in computer science, mathematics, economics or related field


# Process:

## Phone call with Wealthfront Chief Data Officer

- [VINEET SINGH](https://www.linkedin.com/in/vineet-singh-8ba416/) - PhD in AI from Stanford in 1988. 
- Extensive experience with marketing and statistics

notes from call 

- started as wealth management product
- financial planning product, now made avilable to everyone, can specify goals for retirement, college saving, home buying, ... .
- have all data on this, and can project future wealth. 
- high yield cash account product, beginning of a banking services product 
- CD, debit, credit card, etc. 
- self-driving money: idea that they can automate finances for people. to meet short term and long terms savings needs. 
- system can optimize how money from a paycheck or other accounts should flow between cash, investments, savings, based on these goals. 
- accounts for all tax rules, etc. 

Team:

- 170 people in company
- DS team more diverse (9 people (should be doubling lately))
- economists, statisticians, ML, data science, financial, ... .
- Teams;
- investment algorithms
- financial planning optimization
- analytics (product, market, risk), (~ 4 people)
- data products, production ready systems

- Investing in growth: paid marketing, messaging within product to "cross sell", referrals. 
- Almost no paid marketing at all, have had some since introducing the cash account. 
- Still want to apply a science to making it more effective. 
- looking for ideas on growing cash account via a referral program.
- hiring one growth DS for across those areas

<!-- PROCESS -->
Process: 

- this initial meeting
- technical phone screen: more of a filter, statistics and analytics Hypothesis testing, experimental design (first few items I have listed on methods), nothing like RL and contextual bandits, 1 hour long
- homework assignment: programming, 24 hours -- can use Python or R, some analytic questions and need to provide some recommendations
- longer 5 hour interview

Me: 
- finance as a hobby -- Quantopian
- HaaS freelance work

<!-- Increase savings! -->
- Considering Nudges, e.g. maybe showing counterfactuals like how much interest a person would have gotten if they spent X less. 
- I like the figure showing wealth accumulation -- add credible intervals around it if it's based on uncertain investments? 
- Add oldified images of a user later on the timeline, maked that future self more concrete and increases saving behavior?

<!-- work life -->
- What do project pipelines look like -- who is involved, how are tasks ideated and delegated?
- steakholders: marketing team, paid marketing team, 'growth team'
- growth team: a product manager, designer, engineers, and another person, it's just been formed. 
- ** First work on conversion from cash client to investment client.
- ** and on paid marketing side, optimizing marketing on facebook, and Google ad words, and working on attribution to allocate marketing budget. 
- ** Lower customer acquisition costs.
- Identify cash clients who would have biggest benefit from opening investment account.
- regular check in with head of marketing every couple weeks
- Growth DS can look at all of these options (come up with ideas)
- Don't want relationship to be where DS just does what marketing team asks. So DS isn't expected to be marketing expert, but should come up with their own ideas and refine in collaboration with the other teams/partners.

questions; 

- More informaiton about the role?
- Open projects or current directions?
- How big is the DS team?
- Could you tell me a little about your team specifically? 

## Phone call with Ben

<!-- about me -->

- PredictIt, finding arbitrage opportunities, programming them
- Strategy inference, JAGS model to get probability of a strategy being followed on each trial
- Using conjugacy to makde models update fast with streams of data -- Tweet model, RL model for dissertation work
- RL model - an agent is learning a function to plan actions, for this function I uses gaussian basis functions and Bayesian logistic regression

<!-- Questions -->

- Which team are you on? 
- General DS team, each DS owned a specific area. Ben owned financial planning team (path model, projection on dashboard). 
- A/B experimentation and user demographics, trying to figure out what properties of clients lead to an outcome they like. 
- A/B encouraged to come up with own experiments -- Company has a path they want to follow, quarterly objectives for products or things they want to deploy. Those are tested, e.g. predicting off actions if they're going to do X or Y... . 
- Have a lot of client data. DS extract insights from this data
- Have some DE responsibilities, Spark pipelines, Shiny. 
- Scala, production level code. 
- Hadoop, use AWS, often writing ETLs done on .. ?. 
- doubling down on paid marketing bc it had a great response on the cash app. 
- Frequentist much easier even if interpretation harder.. 
- Company founded by economists

- Econ - causal inference?
- Ad attribution?
- have 3rd party aps for ad attribution
- has been attribution issues when people come through multiple referral pages.
- working with impact radious to detect when a user clicks on multiple ads
- different ways to weigh the ads

- What are some of your projects?
- first Spark pipeline took a month
- other weeks when running an experiment to make sure data quality issues have been addressed.
- have inferastructure to run A/B experiment
- Do analyses that A/B platform can't account for
- Do it in R markdown, present in HTML to various teams.
- lot of marketing requests in terms of data quality and impact of marketing experiments
- running queries, in redshift.
- Monday roadmap meeting makes plan for week. Venieet helps prioritize.

- Work culture? Is the workload managable? 
- Once a week with manager, weekly lunch where one DS gives a presentation, and financial meetings.
- growth will have a DS, someone from marketing, someone from DE, ... .

- What are some upcoming projects?
- Your research sounds really cool -- do you do similar work (i.e. develop samplers) at Wealthfront?

- Been really picky with decisions
- been looking for people with a few years of industry experience
- DS has been growing, so maybe opps for general DS roles
- Ben had phone interviews with 
- Technical phone screens have a component to show interest / what you can bring to table
- Educated enthusasiasm, showing you're not shopping around, show you dug deep and understand product and why it's exciting

- use rmd for HW interview
- want to use data to grow the company

- definitely a need for generalists
- but ads now seem to have a qualifier at the end, require T shaped candidate
- had interns this year -- one for research one for DS

- quantity vs quality?
- PhD stands out -- not just someone who did a Kaggle project or a sentiment analyses. 
- Have owned actual research
- Not just a toy dataset, ... 
- Get data understand biases
- For Sr. need ownership. 

- Kinda flexible in terms of what the role is
- Have been some highly qualified people who did presentations
- Might be asked growth related questions
- Could be a general DS role too
- People can get Sr roles out of academia if qualifications fit well.. 

- Wealthfront came in through Insight.
- First time didn't take anyone, took Ben, then didn't take anyone.

- educated enthusasiasm, good answers for why I'm interested in product/company, answer that differs for them vs other investing firms

- SQL or deplyr, 
- joins, etc in deplyr. 

- Used STAN in postdoc for sampling from ~500 params
- Lots of tasks are in prediction realm rather than inference realm.. 
- Predict good outcome based on user behavior
- If opportunity arose to talk about RL work, that'd be good!

- went on 3 onsites, Wealthfront was only offer
- Bosh, Uber, were other onsites
- Uber one part was desasterous.. Didn't undertand what was being asked
- Speaking from experience is what gets Sr roles. 
- Slipping up ok if they're able to catch themselves / adjust quickly. 


## Technical phone screen

Interviewer: [Allen Sirolly](https://www.linkedin.com/in/allen-sirolly-89b0b639/)

From recruiter: "Our technical phone interview is meant to get a sense of the types of research or data problems that excite you. We will inquire about projects you have completed in the past; specifically, we want to hear about your personal contributions to the project and gauge your ability to give background on and extensions to your previous work. You are not permitted to use Google or other reference materials during the interview."

- Sense of problems that excite you
- Inquire about contributions to past projects, understanding of past projects

<!-- my Projects -->
<!-- my Projects -->
<!-- my Projects -->
<!-- my Projects -->

- Insight 
- HaaS

- Quantopian; wanted to create self-driving money for myself
- - replicated XIV
- - Primarily an income investor. Created a strategy conceptually similar to risk parity -- I treated dividends as a measure of risk and weighted stocks inversely to their dividend yields. Quantopian had a bug in dividends paid, so I submitted a ticket showing this with AAPL stock, and stopped using that platform.

- Passion for automated financial decision making: PredictIt formula for guarenteed profits that accounted for relationships between prices, probability theory, and PredictIt fees. This is similar to finding an arbitrage relationship (relations between prices and probability theory) and accounting for taxes (fees). 

<!-- fit for growth team -->

- HaaS work on fb ads and google analytics (talk about these tools)
- Insight work on modeling user conversion from a free-trial to subscriber
- YT channel, casually testing thumbnails

<!-- I like the Products --> 

- Path: Financial planning service that shows a projection of wealth and goals (homebuying, retirement, ...)
- Free financial advice in blogs (read buy vs rent, played with ourse purchase planning tool)
- Investment management and automating established methods (risk parity, modern portfolio theory, .. )
- Portfolio line of credit (Margin Lending)
- Rolling out direct deposit, debit cards

<!-- Other excitement -->

- I also like the principled investment philosophy (Modern protfolio theory, accounting for taxes, ... )

- Personal finance is something that I think about a lot, and a theme in my hobby projects (Quantopian) and research (PredictIt).

- ** excitement: One of my Quantopian ideas was conceptually similar to a wisk parity strategy -- Dividends are a proxy for risk, so I weighted stocks proportional to the reciprocal of their dividend; ($w_i = \frac{1/d_i}{\sum_i 1/d_i}$).
- [Cheap risk parity fund has /$500 mil assets under management](https://www.prnewswire.com/news-releases/wealthfront-cuts-risk-parity-expense-ratio-in-half-to-0-25-300631933.html), the risk parity method equalizes the risk contributions of asset classes within a portfolio
- ** I love the vision of self-driving money, this kind of automation is something I'd want to build for myself if I had the time. 
- [Democratizing quality financial advice](https://blog.wealthfront.com/introducing-free-financial-planning/); I liked the [home guide](https://www.wealthfront.com/home-guide), I've been thinking about renting vs buying for a while now. My BaC card gives 3/% cash back on travel, and airbnb counts for that -- so it's like a 3/% discount on rent.

- Personal finance is something that I think about a lot, and a theme in my hobby projects (Quantopian) and research (PredictIt).

<!-- Vs Bettermint -->

- Wealthfront has better automation, Bettermint pivoted to human advisors
- Self driving money is something I've been working on making for myself through Quantopian and PredictIt.

<!-- Questions / Interest -->

- Which team are you on?

- What is your tech stack?

- What is your like 'methods stack', so what are the statistical tools that you use frequently?
- Frequentist, Bayesian, Causal inference (methods for addressing violations of true randomization e.g. early adopters, noncompliance or contamination, no possible control group (counterfactuals, synthetic controls, causal impact from Google))
- if you make an update available and someoen doesn't upgrade, then the difference you detect might be a different between early adopters and late adopters, rather than between treatment (new app) and control (old app) conditions. 

- Vineet had mentioned working on converting from cash account users to investment management users -- Are there currently attempts at doing this?

- Next steps?


<!-- Value adds / ideas-->

- Why switch from self-management to their portfolio management? 
- - Maybe a tool to compare a person's portfolio to Wealthfront's portfolio? Then a person should switch if switching is easy and their portfolio 
- - - underperforms or 
- - - has higher uncertainty or 
- - - a lower SHARPE? 

- Which blog articles motivate investing? 
- - Exploratory: See which users viewed a blog post
- - Experimental: Suggest blog posts to users (Treatment)
- - focus on Treatment on Treated vs. users who were suggested other posts and viewed them 
- - controls for engagement (viewing suggestion)? 
- - controls for financial motivation (crossover effects i.e. viewing the blog post when it is ont suggestsd (assigned C experienced T))?


# Preparation

<!-- Followup from PM phone call -->

## Ideas

<!-- PROJECT DESCRIPTIONS -->

## Project Descriptions: 

### HaaS freelance work

Situation: 

- Haas stands for housing as a service, it's a membership-based coliving startup.

Task: 

- Want to increase memberships through facebook and google ads. 
- I'm leveraging a little SEO experience to help with designing ads; 
-     Brighter photos, photos with faces, and color schemes that contrast FB's color scheme of white and blue, 
-     thse features are associated with higher CTR for YouTube thumbnails. 
- Becoming familiar with Google Analytics and Facebook Ad Analytics to run A/B tests with these ads

Action: 

- See which drive more interest in CTR, and more conversions in applications for membership, and which attract the demographics that my client wants to attract.

### Insight Project

Situation: 

- 2 week consulting project
- Startup focused on digital workspaces (e.g. google docs)
- Wanted to understand user base.
- Wanted to be able to predict who would convert from a free trial to a paying customer.
- (skip) Wanted to attribute conversion to product features with conversion.

Task:

- Data: 
- Company demographic information, company size and revenue. 
-     Used this to communicate conversion rates by demographic to heads of different teams using tables and figures.
- Account activity data which was a sum of actions taken within an account each day. 
-     I transformed this into cumulative sum instead of daily sum to increase interpretability and modeling ease. 

(skip) Action: 
(skip) - Used cross sections of cumulative account activity data after 7 days since the account was created. 
(skip) - Cast as classification problem, used SMOTE to address class imbalance,
(skip) - used 5-fold CV to evaluate models on AUC, 
(skip) - ended with a RF algorithm for these predictions. 

Result: 

- Delivered presentation and slide deck with tables and figures to a group of team leaders. 
- Delivered a Python script to implement the model, and a slide deck describing the modeling procedure and performance. 

### PredictIt project

Situation:

- Prediction markets aggregate information and incentivize rational behavior, so one would expect the prices to be accurate. 
- At an individual level, lots of fallacies have been established in lab settings.
- I wanted to know if any fallacies would manifest in market prices. 

Results:

- Conjunction fallacy: "Trump" traded higher hand "Republican" for extended period of time.
- Disjunction fallacy: Most market prices add up to something greater than $1, but because of fees it's often not profitable to take advantage of this. 
- CPT subjective probability function: Overpricing of low probability events and Underpricing of high probability events
- -- notably this was highest as expiration approached, a context that is more similar to lab studies that don't have delayed rewards. 

- Now we're working on automating trades based on these and other indights. 

### Quantopian: 

- recreated XIV, fund that trades VIX futures weighted so that the effective days to expiration is approximately 30.
- mean revision
- moving average crossover

### Child bandit modeling

Situation:

- Wanted to know what strategies they followed, and if their strategy changed over time.
- Kids repeatedly chose between two gambling machines

Action:

- I developed a model that inferred the probability of following each strategy on each trial
- Used Bayes' Rule to smooth out these inferences / accumulate information over trials 

Result:

- Kids do seem to switch strategies, probably don't act optimally, and have different strategies depending on age (switchy vs sticky)
- Result: A lot of experiments focus on which strategy best fits all data across trials -- the approach that I took allows for changes in strategies, and the exciting result was an ability to track latent decision making strategies over time. 

Value:

- Implications for user intent modeling

<!-- JUST IN CASE -->

## CI methods

- diff in diff
- causal impact
- synthetic control
- IV analysis

## Deep Dive

### Overview

Summary (2-3 sentences):

### Products

- Path: Financial planning service that shows a projection of wealth and goals (homebuying, retirement, ...)
- Free financial advice in blogs
- Investment management
- Portfolio line of credit (Margin Lending)
- Rolling out direct deposit, debit cards
- [article](https://www.prnewswire.com/news-releases/wealthfront-research-shows-clients-who-regularly-engage-with-automated-financial-advice-save-more-300723506.html): Path usage associated with higher savings, meaning better outcomes for savers (but maybe the savers have higher income / can save more already?)
- [Cheap risk parity fund has /$500 mil assets under management](https://www.prnewswire.com/news-releases/wealthfront-cuts-risk-parity-expense-ratio-in-half-to-0-25-300631933.html), the risk parity method equalizes the risk contributions of asset classes within a portfolio
- ** excitement: One of my Quantopian ideas was conceptually similar to a wisk parity strategy -- Dividends are a proxy for risk, so I weighted stocks proportional to the reciprocal of their dividend; ($w_i = \frac{1/d_i}{\sum_i 1/d_i}$).
- [Democratizing quality financial advice](https://blog.wealthfront.com/introducing-free-financial-planning/); I liked the [home guide](https://www.wealthfront.com/home-guide), I've been thinking about renting vs buying for a while now. My BaC card gives 3/% cash back on travel, and airbnb counts for that -- so it's like a 3/% discount on rent.
- ** Like the vision of self-driving money, this kind of automation is something I's want to build for myself if I had the time. 

Vs Bettermint

- Wealthfront has better automation, Bettermint double backed to human advisors
- 

- Self driving money is something I've been working on making for myself through Quantopian and PredictIt.
- 

### Users

### Use cases

### Dynamics (network, marketplace, ... )

### User Journey and User Flows

### Monetization Strategies

### Major metrics

Growth / retention

Engagement

Monetization

### Possible Questions

How can you help drive key metrics?


What behaviors should the UI drive and how can you make product recommendations?


What data/features would you potentially have access to?


How are certain data products built (recommenders, content feeds)?


How would a site/app reduce fraud?


Based on team you are interviewing for


### Signup process:

- One page for all "Legal Stuff" questions, instead of a page for each question.. 
- - Is there any dropoff on each question? I'm expecting the dropoff for Legal stuff to be lower if it were one page than compared to it being a page for each question.

### Important Metrics:

Growth:

- Weekly new users
- Month over month active account growth

Engagement or value:

- Total deposits
- Total assets tracked

### Culture and Vision

- "We’re here because more people across the economic spectrum deserve to live secure and rewarding lives."

### Business Model

- Offer a high yield savings account 
- Offer funds managed by the author of 'A Random Walk Down Wall Street'
- Use Modern Portfolio Theory, smart beta and tax-loss harvesting for larger accounts. 
- Collect a 0.25% fee on managed funds

## Glassdoor interview questions

- probably puzzle questions.
- behavior : go through the resume.  

### Competition

Wealthfront predacessor was [KaChing](https://venturebeat.com/2019/09/16/google-schedules-pixel-4-hardware-event-for-october-15/), a social network and platform for users to pick a fantasy stock portfolio, and investors to allocate funds acording to the picks of high skill users. KaChing had software that would evaluate the skill of it's users. 

[Betterment](https://www.betterment.com/)

[Wealthfront vs Betterment](https://www.investopedia.com/wealthfront-vs-betterment-4587963)

- 











